import type { BadgeDefinition } from "../lib/types";

export const badges: BadgeDefinition[] = [
  {
    id: "first-step",
    name: "はじめの一歩",
    description: "最初のステージを一つ完了しました。",
    icon: "🌱",
    encouragement: "自分で触ってみたことが、いちばん大きな一歩です。",
    xpBonus: 10,
    unlockCondition: { kind: "completed-stages", count: 1 },
  },
  {
    id: "pc-beginner",
    name: "PCを試してみた",
    description: "PCモードのステージを三つ完了しました。",
    icon: "🖥️",
    encouragement: "違う画面でも、共通する手がかりが見えてきました。",
    xpBonus: 15,
    unlockCondition: { kind: "completed-stages", count: 3, device: "pc" },
  },
  {
    id: "mobile-beginner",
    name: "スマホを試してみた",
    description: "スマートフォンモードのステージを三つ完了しました。",
    icon: "📱",
    encouragement: "タップやメニューを落ち着いて試せています。",
    xpBonus: 15,
    unlockCondition: { kind: "completed-stages", count: 3, device: "mobile" },
  },
  {
    id: "researcher",
    name: "調べる名人",
    description: "辞典、FAQ、ヘルプ検索を使う行動を三回行いました。",
    icon: "🔎",
    encouragement: "分からないときに、自分で手がかりを探せました。",
    xpBonus: 20,
    unlockCondition: { kind: "research-actions", count: 3 },
  },
  {
    id: "recovery-expert",
    name: "もどせた！",
    description: "戻る、閉じる、元に戻すで三回復旧しました。",
    icon: "↩️",
    encouragement: "間違えても戻せると分かれば、安心して試せます。",
    xpBonus: 20,
    unlockCondition: { kind: "recovery-actions", count: 3 },
  },
  {
    id: "safety-checker",
    name: "安全確認できました",
    description: "注意が必要な操作を読み、適切にキャンセルしました。",
    icon: "🛡️",
    encouragement: "何でも押すのではなく、立ち止まる判断ができました。",
    xpBonus: 20,
    unlockCondition: { kind: "safe-cancels", count: 2 },
  },
  {
    id: "curious-explorer",
    name: "探索上手",
    description: "フリープレイで十種類の操作を試しました。",
    icon: "🧭",
    encouragement: "『押したらどうなるだろう』を安全に確かめられました。",
    xpBonus: 25,
    unlockCondition: { kind: "free-play-actions", count: 10 },
  },
  {
    id: "pc-and-mobile",
    name: "PCもスマホも",
    description: "PCとスマートフォン、両方のモードを体験しました。",
    icon: "🔄",
    encouragement: "機器が変わっても、知っている考え方を応用できます。",
    xpBonus: 25,
    unlockCondition: { kind: "used-device-modes", count: 2 },
  },
  {
    id: "another-way",
    name: "別の道を発見",
    description: "案内とは別の安全な方法で課題を解決しました。",
    icon: "💡",
    encouragement: "操作は一つだけではありません。自分で方法を選べています。",
    xpBonus: 25,
    unlockCondition: { kind: "alternative-solutions", count: 1 },
  },
  {
    id: "independent-step",
    name: "自立への一歩",
    description: "WORLD 7のPC・スマホの自立チャレンジを完了しました。",
    icon: "🌟",
    encouragement: "目的から考え、必要な操作を自分で組み合わせられました。",
    xpBonus: 40,
    unlockCondition: { kind: "completed-world", worldId: "world-7" },
  },
];
