import type { GlossaryTerm } from "../lib/types";

export const glossaryTerms: GlossaryTerm[] = [
  {
    id: "app",
    term: "アプリ",
    reading: "あぷり",
    category: "screen",
    shortDescription: "目的に合わせて使う道具です。",
    description:
      "文章を書く、写真を見る、メールを送るなど、決まった役割を持つデジタルの道具です。パソコンでは『ソフト』と呼ばれることもあります。",
    example: "メモ、ブラウザ、メールは、それぞれ別のアプリです。",
    relatedTermIds: ["window", "home-screen"],
    tryIt: "練習画面でアプリを一つ開き、ホームへ戻ってみましょう。",
  },
  {
    id: "window",
    term: "ウィンドウ",
    reading: "うぃんどう",
    category: "screen",
    shortDescription: "パソコンでアプリや内容を表示する四角い枠です。",
    description:
      "一つの画面の中で、複数のアプリや資料を別々に表示するための枠です。閉じても、保存済みのアプリやファイルまで消えるわけではありません。",
    example: "ブラウザのウィンドウを閉じて、デスクトップへ戻ります。",
    relatedTermIds: ["app", "tab", "popup"],
  },
  {
    id: "home-screen",
    term: "ホーム画面",
    reading: "ほーむがめん",
    category: "screen",
    shortDescription: "スマートフォンでアプリを選ぶ出発点の画面です。",
    description:
      "アプリのマークが並ぶ基本の画面です。迷ったときはホームへ戻ると、別のアプリを探し直せます。",
    example: "ホーム画面からメモのアプリを開きます。",
    relatedTermIds: ["app", "menu"],
    tryIt: "練習スマートフォンでアプリを開き、ホームボタンで戻ってみましょう。",
  },
  {
    id: "menu",
    term: "メニュー",
    reading: "めにゅー",
    category: "screen",
    shortDescription: "使える機能をまとめた一覧です。",
    description:
      "画面に全部を並べきれないとき、操作や設定を一か所にまとめて見せる一覧です。押して中を見るだけなら、多くの場合は安全です。",
    example: "メニューを開き、『表示設定』を探します。",
    relatedTermIds: ["more-menu", "settings"],
    tryIt: "三本線や三点のマークを探して、メニューだけ開いてみましょう。",
  },
  {
    id: "more-menu",
    term: "三点メニュー",
    reading: "さんてんめにゅー",
    category: "screen",
    shortDescription: "三つの点で表される、追加機能の入口です。",
    description:
      "縦または横に並んだ三つの点は、『ほかにも操作があります』という合図としてよく使われます。中には共有、設定、削除などが入ることがあります。",
    example: "右上の三点メニューから文字サイズを変更します。",
    relatedTermIds: ["menu", "settings", "safe-operation"],
  },
  {
    id: "settings",
    term: "設定",
    reading: "せってい",
    category: "screen",
    shortDescription: "アプリや端末の動き方・見え方を変える場所です。",
    description:
      "文字の大きさ、通知、音などを自分に合わせて調整する場所です。歯車のマークで表されることがよくあります。",
    example: "設定で文字を大きくして、読みやすくします。",
    relatedTermIds: ["menu", "more-menu", "safe-operation"],
    tryIt: "練習画面の歯車を開き、どんな項目があるか見るだけ試してみましょう。",
  },
  {
    id: "popup",
    term: "ポップアップ",
    reading: "ぽっぷあっぷ",
    category: "screen",
    shortDescription: "今の画面の上に、一時的に重なって出る小さな画面です。",
    description:
      "お知らせ、確認、入力などのために表示されます。閉じる、キャンセル、画面外を押すなどで元の画面へ戻れる場合があります。",
    example: "案内のポップアップを閉じて、後ろの画面を確認します。",
    relatedTermIds: ["window", "menu", "safe-operation"],
  },
  {
    id: "browser",
    term: "ブラウザ",
    reading: "ぶらうざ",
    category: "internet",
    shortDescription: "インターネットのページを見るためのアプリです。",
    description:
      "Webサイトを開いたり検索したりする道具です。検索サービスそのものとは別ですが、ブラウザの中から検索できます。",
    example: "ブラウザを開いて、市民センターの情報を検索します。",
    relatedTermIds: ["search", "url", "tab", "link"],
    tryIt: "練習ブラウザを開き、上部にある検索欄を探してみましょう。",
  },
  {
    id: "tab",
    term: "タブ",
    reading: "たぶ",
    category: "internet",
    shortDescription: "一つのウィンドウで複数のページを切り替える見出しです。",
    description:
      "本のしおりのように、開いたページを残したまま別のページを見るために使います。タブを閉じてもブラウザ全体は閉じません。",
    example: "二つの検索結果を別のタブで開いて比べます。",
    relatedTermIds: ["browser", "window", "link"],
  },
  {
    id: "search",
    term: "検索",
    reading: "けんさく",
    category: "internet",
    shortDescription: "知りたいことに関係する言葉を使って情報を探すことです。",
    description:
      "長い質問をそのまま書く方法も、重要な言葉だけを並べる方法もあります。結果が合わないときは、言葉を足したり変えたりします。",
    example: "『市民センター 休館日』のように、場所と知りたいことを一緒に検索します。",
    relatedTermIds: ["browser", "link", "faq", "help"],
    tryIt: "場所の名前と知りたい内容を二語にして、練習検索へ入れてみましょう。",
  },
  {
    id: "link",
    term: "リンク",
    reading: "りんく",
    category: "internet",
    shortDescription: "押すと別のページや場所へ移動できる文字や画像です。",
    description:
      "青い文字や下線付きの文字で表されることがあります。開く前に、説明や行き先を確かめる習慣が役立ちます。",
    example: "検索結果の『公式案内』というリンクを開きます。",
    relatedTermIds: ["url", "browser", "tab"],
  },
  {
    id: "url",
    term: "URL",
    reading: "ゆーあーるえる",
    category: "internet",
    shortDescription: "インターネット上のページの住所です。",
    description:
      "同じ名前のページを区別し、特定の場所へ移動するための文字列です。ブラウザ上部の欄などに表示されます。",
    example: "URLの始まりやサイト名を見て、行き先を確かめます。",
    relatedTermIds: ["browser", "link"],
  },
  {
    id: "account",
    term: "アカウント",
    reading: "あかうんと",
    category: "account",
    shortDescription: "サービスの中で自分を見分けてもらうための登録です。",
    description:
      "自分の設定やデータを保存するための利用者情報です。同じ端末に複数のアカウントが入ることもあります。",
    example: "右上の人物マークから、使っているアカウントを確認します。",
    relatedTermIds: ["login", "logout", "user-id", "password"],
  },
  {
    id: "login",
    term: "ログイン",
    reading: "ろぐいん",
    category: "account",
    shortDescription: "自分のアカウントを使える状態にすることです。",
    description:
      "IDやパスワードなどを使って、サービスに自分だと確認してもらいます。共有端末では、使い終わった後のログアウトも大切です。",
    example: "練習用のIDでログイン画面を進めます。",
    relatedTermIds: ["account", "logout", "user-id", "password"],
  },
  {
    id: "logout",
    term: "ログアウト",
    reading: "ろぐあうと",
    category: "account",
    shortDescription: "アカウントを使っている状態を終えることです。",
    description:
      "アカウント自体を削除する操作ではありません。共有端末で、ほかの人に自分の情報を見られないようにするときに使います。",
    example: "共有パソコンでは、使い終わったらログアウトします。",
    relatedTermIds: ["account", "login", "safe-operation"],
  },
  {
    id: "user-id",
    term: "ID",
    reading: "あいでぃー",
    category: "account",
    shortDescription: "サービスが利用者を見分けるための名前や番号です。",
    description:
      "メールアドレスや決められた文字列がIDとして使われます。パスワードとは役割が違います。",
    example: "ログイン画面では、IDとパスワードを別々の欄に入れます。",
    relatedTermIds: ["account", "login", "password"],
  },
  {
    id: "password",
    term: "パスワード",
    reading: "ぱすわーど",
    category: "account",
    shortDescription: "本人であることを確かめるための秘密の文字列です。",
    description:
      "ほかの人に教えたり、練習サイトやAIへ書き込んだりしません。忘れた場合は『パスワードを忘れた方』などから再設定できます。",
    example: "練習では本物のパスワードを使わず、用意された架空の文字列を使います。",
    relatedTermIds: ["login", "authentication-code", "safe-operation"],
  },
  {
    id: "authentication-code",
    term: "認証コード",
    reading: "にんしょうこーど",
    category: "account",
    shortDescription: "本人確認のため、一時的に届く数字や文字です。",
    description:
      "メールやSMSなどに送られ、短い時間だけ使えることがあります。自分から始めていない操作のコードは入力しません。",
    example: "パスワード再設定を始めた後、練習メールに届いたコードを確認します。",
    relatedTermIds: ["password", "email", "login"],
  },
  {
    id: "email",
    term: "メール",
    reading: "めーる",
    category: "internet",
    shortDescription: "インターネットを使って文章やファイルを送受信する仕組みです。",
    description:
      "宛先、件名、本文を確認して送ります。知らない相手からのリンクや添付ファイルは、すぐ開かず慎重に確かめます。",
    example: "練習メールへ資料を添付し、送信前に内容を確認します。",
    relatedTermIds: ["attachment", "account", "link"],
  },
  {
    id: "file",
    term: "ファイル",
    reading: "ふぁいる",
    category: "file",
    shortDescription: "文章、写真、音声などを一つのまとまりとして保存したものです。",
    description:
      "名前や種類を手がかりにして探します。同じ名前でも、保存場所が違えば別のファイルの場合があります。",
    example: "『参加案内.pdf』というファイルを開きます。",
    relatedTermIds: ["folder", "download", "upload", "attachment"],
  },
  {
    id: "folder",
    term: "フォルダ",
    reading: "ふぉるだ",
    category: "file",
    shortDescription: "ファイルを分けて整理する入れ物です。",
    description:
      "書類を入れるケースのように、関連するファイルをまとめます。フォルダの中に別のフォルダを作ることもできます。",
    example: "ダウンロードした資料を『提出用』フォルダへ移動します。",
    relatedTermIds: ["file", "download", "drag"],
  },
  {
    id: "download",
    term: "ダウンロード",
    reading: "だうんろーど",
    category: "file",
    shortDescription: "インターネット上のファイルを自分の端末へ受け取ることです。",
    description:
      "受け取ったファイルは『ダウンロード』というフォルダに入ることがよくあります。知らないファイルは安全を確認してから開きます。",
    example: "サイトから資料をダウンロードし、ファイル画面で探します。",
    relatedTermIds: ["file", "folder", "upload", "safe-operation"],
  },
  {
    id: "upload",
    term: "アップロード",
    reading: "あっぷろーど",
    category: "file",
    shortDescription: "端末にあるファイルをインターネット上へ渡すことです。",
    description:
      "応募フォームや共有サービスへ写真や書類を送るときに使います。送る相手や公開範囲を先に確認します。",
    example: "フォームの『ファイルを選ぶ』から、提出する資料をアップロードします。",
    relatedTermIds: ["file", "download", "attachment", "share"],
  },
  {
    id: "attachment",
    term: "添付",
    reading: "てんぷ",
    category: "file",
    shortDescription: "メールやメッセージにファイルを付け加えることです。",
    description:
      "クリップのマークで表されることがあります。送る前に、正しいファイルか、個人情報が含まれていないかを確認します。",
    example: "『参加案内.pdf』を練習メールへ添付します。",
    relatedTermIds: ["file", "email", "upload", "safe-operation"],
  },
  {
    id: "share",
    term: "共有",
    reading: "きょうゆう",
    category: "file",
    shortDescription: "写真や情報を別の人やアプリで使えるように渡すことです。",
    description:
      "共有マークから、渡す相手やアプリを選びます。公開範囲や送り先を確認してから実行します。",
    example: "写真を選び、共有先としてメールを選びます。",
    relatedTermIds: ["attachment", "upload", "safe-operation"],
  },
  {
    id: "copy",
    term: "コピー",
    reading: "こぴー",
    category: "operation",
    shortDescription: "選んだ文字や内容を、元を残したまま一時的に覚えさせる操作です。",
    description:
      "コピーしただけでは画面に変化が少ないことがあります。その後に貼り付けをすると、別の場所で同じ内容を使えます。",
    example: "案内の時刻をコピーし、メモへ貼り付けます。",
    relatedTermIds: ["paste", "file"],
    tryIt: "練習用の文章をコピーし、元の文章が残っていることを確認しましょう。",
  },
  {
    id: "paste",
    term: "貼り付け",
    reading: "はりつけ",
    category: "operation",
    shortDescription: "コピーした内容を、選んだ場所へ入れる操作です。",
    description:
      "『ペースト』と呼ばれることもあります。貼り付け先を先に選ぶと、どこに入るか分かりやすくなります。",
    example: "コピーした住所を、練習メモの空欄へ貼り付けます。",
    relatedTermIds: ["copy"],
  },
  {
    id: "drag",
    term: "ドラッグ",
    reading: "どらっぐ",
    category: "operation",
    shortDescription: "押したまま動かして、ものを別の場所へ移す操作です。",
    description:
      "マウスではボタンを押したまま動かし、スマートフォンでは指を離さず動かします。難しい場合は『移動』メニューを使えることもあります。",
    example: "ファイルをフォルダの上までドラッグして移動します。",
    relatedTermIds: ["file", "folder", "scroll"],
  },
  {
    id: "scroll",
    term: "スクロール",
    reading: "すくろーる",
    category: "operation",
    shortDescription: "画面に入りきらない続きを上下や左右に動かして見る操作です。",
    description:
      "ボタンが見つからないとき、画面の下に続きが隠れている場合があります。少しずつ動かして探します。",
    example: "下へスクロールすると、保存ボタンが見つかりました。",
    relatedTermIds: ["window", "drag"],
    tryIt: "練習ページを下へ動かし、続きを見つけてから上へ戻してみましょう。",
  },
  {
    id: "undo",
    term: "元に戻す",
    reading: "もとにもどす",
    category: "operation",
    shortDescription: "直前の変更を取り消し、一つ前の状態へ戻す操作です。",
    description:
      "『Undo』や左向きに曲がった矢印で表されることがあります。戻るボタンは前の画面へ、元に戻すは変更前へ戻すという違いがあります。",
    example: "ファイルを違う場所へ動かしたので、元に戻すを使います。",
    relatedTermIds: ["safe-operation", "error-message"],
    tryIt: "練習画面で変更を一つ行い、『1つ前に戻す』を試してみましょう。",
  },
  {
    id: "help",
    term: "ヘルプ",
    reading: "へるぷ",
    category: "help",
    shortDescription: "使い方や困ったときの解決方法を調べる場所です。",
    description:
      "分からないことを自分で調べるための入口です。画面に出ている言葉や、やりたいことを検索すると見つけやすくなります。",
    example: "ヘルプで『保存ボタン 見つからない』と検索します。",
    relatedTermIds: ["search", "faq", "error-message"],
  },
  {
    id: "faq",
    term: "FAQ",
    reading: "えふえーきゅー",
    category: "help",
    shortDescription: "よくある質問と答えをまとめた場所です。",
    description:
      "同じところで困った人向けの解決方法が見つかることがあります。『よくある質問』と日本語で書かれる場合もあります。",
    example: "FAQで『ダウンロードしたファイルが見つからない』を探します。",
    relatedTermIds: ["help", "search"],
  },
  {
    id: "error-message",
    term: "エラーメッセージ",
    reading: "えらーめっせーじ",
    category: "help",
    shortDescription: "うまく進めなかった理由や手がかりを知らせる文章です。",
    description:
      "必ずしも故障を意味しません。番号、太字の言葉、直前にしていた操作を確認すると、検索や質問に使えます。",
    example: "『E-204』という番号と『ファイル』という言葉をメモして調べます。",
    relatedTermIds: ["help", "search", "undo", "ai"],
  },
  {
    id: "ai",
    term: "AI",
    reading: "えーあい",
    category: "help",
    shortDescription: "質問に答えたり、文章作りを手伝ったりする仕組みです。",
    description:
      "やりたいこと、表示された内容、試したことを伝えると、より役立つ答えを得やすくなります。本物のパスワードや個人情報は入力しません。",
    example: "『PDFを開きたい。E-204と出た。再起動は試した』のように質問します。",
    relatedTermIds: ["search", "help", "error-message", "safe-operation"],
  },
  {
    id: "safe-operation",
    term: "安全に試せる操作",
    reading: "あんぜんにためせるそうさ",
    category: "safety",
    shortDescription: "結果を確認しながら、元に戻しやすい操作です。",
    description:
      "画面を開く、メニューを見る、戻る、閉じる、検索するなどは比較的試しやすい操作です。削除、購入、公開、送信、個人情報入力は立ち止まって確認します。",
    example: "設定メニューを見るだけ試し、削除の確認画面ではキャンセルします。",
    relatedTermIds: ["undo", "settings", "share", "password"],
    tryIt: "練習画面でメニューを一つ開き、何も変更せず閉じてみましょう。",
  },
];
