import type {
  DangerDefinition,
  EnvironmentOperation,
  EnvironmentOperations,
  EvidenceKind,
  EvidenceRequirement,
  JourneyArea,
  JourneyAreaId,
  LearningEnvironment,
  MissionDefinition,
  MissionId,
  MissionSuccess,
  ProgressiveHints,
  StateRequirement,
} from "../lib/journey-types";
import { learningEnvironments } from "../lib/journey-types";

type OperationDraft = readonly [steps: readonly string[], difference: string];
type StateDraft = readonly [key: string, description: string];
type EvidenceDraft = readonly [
  key: string,
  kind: EvidenceKind,
  description: string,
  required?: boolean,
];

const environmentLabels: Record<LearningEnvironment, string> = {
  windows: "Windows風",
  mac: "Mac風",
  iphone: "iPhone風",
  android: "Android風",
};

function makeOperation(
  environment: LearningEnvironment,
  [steps, difference]: OperationDraft,
): EnvironmentOperation {
  return { label: environmentLabels[environment], steps, difference };
}

function environmentOperations(
  windows: OperationDraft,
  mac: OperationDraft,
  iphone: OperationDraft,
  android: OperationDraft,
): EnvironmentOperations {
  return {
    windows: makeOperation("windows", windows),
    mac: makeOperation("mac", mac),
    iphone: makeOperation("iphone", iphone),
    android: makeOperation("android", android),
  };
}

function progressiveHints(
  direction: string,
  feature: string,
  windows: string,
  mac: string,
  iphone: string,
  android: string,
): ProgressiveHints {
  return {
    direction,
    feature,
    action: { windows, mac, iphone, android },
  };
}

function missionSuccess(
  summary: string,
  stateDrafts: readonly StateDraft[],
  evidenceDrafts: readonly EvidenceDraft[],
): MissionSuccess {
  const states: StateRequirement[] = stateDrafts.map(([key, description]) => ({
    key,
    description,
  }));
  const evidence: EvidenceRequirement[] = evidenceDrafts.map(
    ([key, kind, description, required = true]) => ({ key, kind, description, required }),
  );
  return { summary, states, evidence, orderIndependent: true };
}

function danger(level: DangerDefinition["level"], message: string): DangerDefinition {
  const labels: Record<DangerDefinition["level"], string> = {
    green: "試してよい",
    yellow: "内容を確認",
    red: "確定前に止まる",
  };
  return { level, label: labels[level], message };
}

export const journeyAreas: readonly JourneyArea[] = [
  {
    id: "touch-and-move",
    order: 1,
    title: "クリックと画面操作",
    description: "左クリック、スクロール、右クリック、コピー・貼り付けを練習します。",
    outcome: "画面の変化を見ながら、安全に小さく試せる。",
    missionIds: ["pointer", "scroll", "context", "recovery"],
  },
  {
    id: "navigate-screens",
    order: 2,
    title: "画面とアプリの操作",
    description: "戻る、閉じる、切り替える。今いる場所を見失わない練習です。",
    outcome: "二つの画面を行き来し、作業を失わず戻れる。",
    missionIds: ["navigation", "open-close", "app-switch", "menu-discovery"],
  },
  {
    id: "work-with-text",
    order: 3,
    title: "文字を扱う",
    description: "入力、選択、コピー、修正を本物に近い操作で試します。",
    outcome: "必要な文字だけを扱い、間違いを部分的に直せる。",
    missionIds: ["typing", "text-selection", "copy-paste", "edit-undo"],
  },
  {
    id: "find-and-check",
    order: 4,
    title: "探して確かめる",
    description: "検索語を工夫し、二つの情報と発信元を比べます。",
    outcome: "見つけた情報をそのまま信じず、根拠を確かめられる。",
    missionIds: ["browser-search", "search-refine", "tabs-compare", "source-check"],
  },
  {
    id: "files-and-photos",
    order: 5,
    title: "ファイルと写真",
    description: "保存場所を理解し、整理、ダウンロード、添付を行います。",
    outcome: "必要な資料を後から見つけ、正しい相手へ準備できる。",
    missionIds: ["file-concepts", "file-organize", "download-locate", "attach-review"],
  },
  {
    id: "proceed-safely",
    order: 6,
    title: "安全に進める",
    description: "許可、認証、送信、怪しい案内で立ち止まって考えます。",
    outcome: "何でも拒否せず、目的と危険度から安全に判断できる。",
    missionIds: ["permission-decision", "account-recovery", "form-review", "suspicious-message"],
  },
  {
    id: "solve-problems",
    order: 7,
    title: "困ったときの対処",
    description: "エラーを読み、原因を切り分け、助けや別の道を探します。",
    outcome: "困った状態を言葉にし、安全な方法で復旧できる。",
    missionIds: ["error-reading", "wifi-recovery", "help-search", "alternate-solution"],
  },
  {
    id: "independent-challenge",
    order: 8,
    title: "まとめの練習",
    description: "目的だけを見て、これまでの力を組み合わせます。",
    outcome: "初めての画面でも観察、判断、復旧を組み合わせて進める。",
    missionIds: [
      "independent-research",
      "independent-file",
      "independent-settings",
      "independent-troubleshoot",
    ],
  },
];

export const journeyMissions: readonly MissionDefinition[] = [
  {
    id: "pointer",
    areaId: "touch-and-move",
    order: 1,
    title: "日付をクリックする",
    mission: "カレンダーの『7月19日』をクリックしてください。",
    objective: "一度だけ選び、画面がどう変わるかを見る。",
    competency: "押せる物を見分け、単押しと二度押しを使い分ける。",
    competencyIds: ["C1"],
    prerequisites: [],
    transferTo: ["scroll", "context", "typing", "text-selection"],
    guidance: "show",
    estimatedMinutes: 5,
    interactions: ["pointer"],
    realWorldActions: ["ポインターを動かす", "一度選ぶ", "PCでは二度押して開く"],
    commonConcepts: ["選択", "選択表示", "開く", "誤選択は選び直せる"],
    environmentOperations: environmentOperations(
      [["矢印を『7月19日』へ動かす", "マウスの左ボタンを1回押す", "日付の色が変わったことを確認する"], "1回押す操作を『クリック』といいます。"],
      [["矢印を『7月19日』へ動かす", "マウスまたはトラックパッドを1回押す", "日付の色が変わったことを確認する"], "1回押す操作を『クリック』といいます。"],
      [["予定を一度タップする", "色や画面の変化を確認する"], "iPhoneでは通常、一度のタップで選択や画面移動をします。"],
      [["予定を一度タップする", "色や画面の変化を確認する"], "Androidも一度のタップが基本ですが、見た目は機種で異なります。"],
    ),
    hints: progressiveHints(
      "色や形が変わりそうな場所を一つ探しましょう。",
      "予定表の『7月19日』が目印です。",
      "予定へポインターを合わせ、左ボタンを一度押します。",
      "予定へポインターを合わせ、トラックパッドまたはマウスを一度クリックします。",
      "『7月19日』を指で一度タップします。",
      "『7月19日』を指で一度タップします。",
    ),
    afterCompletion: "ねらった場所を選び、違ったときも選び直せます。",
    xp: 30,
    danger: danger("green", "選ぶ、開く、見直す操作は何度でも試せます。"),
    success: missionSuccess(
      "指定予定が選ばれている。誤選択があっても最終状態で判定する。",
      [["selectedItemId", "選択中の予定が目標IDになっている"]],
      [
        ["selectionChangeObserved", "observation", "選択表示の変化を確認した"],
        ["wrongSelectionRecovered", "recovery", "誤選択を自分で直した", false],
      ],
    ),
  },
  {
    id: "scroll",
    areaId: "touch-and-move",
    order: 2,
    title: "画面をスクロールする",
    mission: "お知らせをスクロールし、『持ち物』を見つけてください。",
    objective: "画面外に続きがあると気づき、必要な位置へ動かす。",
    competency: "縦と横のスクロール、動く範囲、現在地を見分ける。",
    competencyIds: ["C1", "C2"],
    prerequisites: ["pointer"],
    transferTo: ["navigation", "form-review", "file-concepts"],
    guidance: "show",
    estimatedMinutes: 5,
    interactions: ["scroll", "pointer"],
    realWorldActions: ["お知らせの中へポインターを置く", "縦にスクロールする", "必要な項目を左クリックする"],
    commonConcepts: ["画面外の続き", "縦スクロール", "スクロールする範囲", "必要な項目で止める"],
    environmentOperations: environmentOperations(
      [["お知らせの中にポインターを置く", "マウスホイールを下へ回して『持ち物』までスクロールする", "『持ち物　青いタオル』を左クリックする"], "ポインターを置いたお知らせの中だけが動きます。"],
      [["お知らせの中にポインターを置く", "トラックパッドを2本指で上へ動かして『持ち物』までスクロールする", "『持ち物　青いタオル』をクリックする"], "指の動きと内容の動きの向きは設定で変わる場合があります。"],
      [["お知らせの上に指を置く", "画面を上へスワイプして『持ち物』までスクロールする", "『持ち物　青いタオル』をタップする"], "指を動かすと、お知らせの内容が動きます。"],
      [["お知らせの上に指を置く", "画面を上へスワイプして『持ち物』までスクロールする", "『持ち物　青いタオル』をタップする"], "指を動かすと、お知らせの内容が動きます。"],
    ),
    hints: progressiveHints(
      "見えている所だけでなく、その先がないか確かめましょう。",
      "お知らせの中にポインターや指を置いて、内容を動かします。",
      "お知らせ上でホイールを下へ回し、『持ち物』で止めます。",
      "お知らせ上で2本指を使い、『持ち物』まで内容を動かします。",
      "お知らせを上へスワイプし、『持ち物』が見えたら止めます。",
      "お知らせを上へスワイプし、『持ち物』が見えたら止めます。",
    ),
    afterCompletion: "見えない情報も、続きがないか確かめられます。",
    xp: 35,
    danger: danger("green", "読む場所を動かすだけなので安全に繰り返せます。"),
    success: missionSuccess(
      "持ち物の項目が見える位置にあり、内容を確認している。",
      [["targetSectionVisible", "『持ち物』が可視範囲に入っている"]],
      [
        ["verticalScrollUsed", "interaction", "縦方向の続きへ移動した"],
        ["horizontalScrollObserved", "observation", "横方向に動く領域も確認した"],
      ],
    ),
  },
  {
    id: "context",
    areaId: "touch-and-move",
    order: 3,
    title: "フォルダーのメニューを開く",
    mission: "『参考資料』フォルダーのメニューを開き、『情報を見る』を押してください。",
    objective: "対象に応じた補助メニューを開き、安全な項目だけ使う。",
    competency: "右クリック、Controlクリック、長押しで隠れた操作を見つける。",
    competencyIds: ["C1", "C2", "C5"],
    prerequisites: ["pointer", "scroll"],
    transferTo: ["recovery", "file-organize", "alternate-solution"],
    guidance: "coach",
    estimatedMinutes: 6,
    interactions: ["context-menu", "menu-discovery", "pointer"],
    realWorldActions: ["補助メニューを開く", "項目を読む", "詳細だけを見る", "削除を確定しない"],
    commonConcepts: ["対象ごとのメニュー", "長押し", "詳細", "削除前の確認"],
    environmentOperations: environmentOperations(
      [["『参考資料』フォルダーを右クリックする", "表示された『情報を見る』をクリックする"], "右クリックすると、そのフォルダーに使える操作が表示されます。"],
      [["『参考資料』フォルダーをControlクリックまたは2本指クリックする", "表示された『情報を見る』をクリックする"], "押し方はMacの設定によって異なります。"],
      [["『参考資料』フォルダーを触れたまま少し待つ", "表示された『情報』を押す"], "触れたまま待つ操作を『長押し』といいます。"],
      [["『参考資料』フォルダーを長押しする", "表示された『詳細』を押す"], "メニューの位置はアプリによって異なります。"],
    ),
    hints: progressiveHints(
      "写真そのものから、見えていない操作を呼び出せます。",
      "補助メニューを開き、『詳細』に近い言葉を探します。",
      "写真を右クリックし、『詳細を見る』を選びます。",
      "写真をControlクリックまたは2本指クリックし、『情報を見る』を選びます。",
      "写真を長押しし、表示されたメニューの『情報』をタップします。",
      "写真を長押しし、表示された『詳細』をタップします。",
    ),
    afterCompletion: "画面に見えていない操作も、対象から安全に探せます。",
    xp: 40,
    danger: danger("yellow", "メニューを見るのは安全です。削除や共有は内容を確認してから進めます。"),
    success: missionSuccess(
      "写真の補助メニューから詳細を表示し、削除は確定していない。",
      [
        ["contextualMenuOpened", "対象の補助メニューが開かれた"],
        ["detailsViewed", "写真の詳細が表示された"],
        ["deleteNotCommitted", "削除が確定されていない"],
      ],
      [
        ["menuItemsInspected", "observation", "メニュー項目を見比べた"],
        ["deleteCancelRecovered", "recovery", "削除確認から取り消した", false],
      ],
    ),
  },
  {
    id: "recovery",
    areaId: "touch-and-move",
    order: 4,
    title: "文章をコピーして貼り付ける",
    mission: "見本文の『集合場所：中央公民館』をコピーし、メモへ貼り付けてください。",
    objective: "元の文章を残したまま、同じ内容を別の場所で使う。",
    competency: "文字の選択、コピー、貼り付けを画面のメニューで行う。",
    competencyIds: ["C1", "C2"],
    prerequisites: ["pointer", "context"],
    transferTo: ["typing", "text-selection", "copy-paste", "file-organize"],
    guidance: "show",
    estimatedMinutes: 7,
    interactions: ["text-selection", "copy-paste", "context-menu"],
    realWorldActions: ["必要な文章を選択する", "右クリックメニューでコピーする", "メモへ貼り付ける"],
    commonConcepts: ["文字の選択", "コピー", "貼り付け", "元の文章は残る"],
    environmentOperations: environmentOperations(
      [["『集合場所：中央公民館』を左ボタンを押したままドラッグする", "選択した文章を右クリックして『コピー』を左クリックする", "メモ欄を右クリックして『貼り付け』を左クリックする"], "コピーしても、元の文章は消えません。"],
      [["『集合場所：中央公民館』をトラックパッドで選択する", "選択した文章をControlクリックして『コピー』をクリックする", "メモ欄をControlクリックして『貼り付け』をクリックする"], "コピーしても、元の文章は消えません。"],
      [["『集合場所：中央公民館』を長押しして選択範囲を合わせる", "『コピー』をタップする", "メモ欄を長押しして『ペースト』をタップする"], "コピーしても、元の文章は消えません。"],
      [["『集合場所：中央公民館』を長押しして選択範囲を合わせる", "『コピー』をタップする", "メモ欄を長押しして『貼り付け』をタップする"], "コピーしても、元の文章は消えません。"],
    ),
    hints: progressiveHints(
      "まず、見本文の中から必要な一文だけを選択します。",
      "選択した文章の上でメニューを開き、『コピー』を使います。",
      "文章をドラッグして選択し、右クリックの『コピー』、メモ欄を右クリックして『貼り付け』を左クリックします。",
      "文章を選択し、Controlクリックの『コピー』、メモ欄の『貼り付け』をクリックします。",
      "文章を長押しして『コピー』、メモ欄を長押しして『ペースト』をタップします。",
      "文章を長押しして『コピー』、メモ欄を長押しして『貼り付け』をタップします。",
    ),
    afterCompletion: "元の文章を消さず、同じ内容をメモへ貼り付けられました。",
    xp: 45,
    danger: danger("green", "コピーでは元の文章は消えません。何度でも練習できます。"),
    success: missionSuccess(
      "元の文章が残り、メモに『集合場所：中央公民館』が貼り付けられている。",
      [
        ["sourceText", "元の見本文が残っている"],
        ["destinationValue", "メモに必要な文章が入っている"],
      ],
      [
        ["copyUsed", "interaction", "コピー操作を使った"],
        ["pasteUsed", "interaction", "貼り付け操作を使った"],
      ],
    ),
  },
  {
    id: "navigation",
    areaId: "navigate-screens",
    order: 5,
    title: "元の場所へ帰る",
    mission: "お知らせを読み、一覧、ホーム、履歴へ戻りましょう。",
    objective: "戻る、ホーム、履歴を目的に合わせて使い分ける。",
    competency: "現在地、直前の画面、アプリの起点を区別する。",
    competencyIds: ["C2", "C6"],
    prerequisites: ["recovery", "scroll"],
    transferTo: ["open-close", "browser-search", "file-concepts"],
    guidance: "show",
    estimatedMinutes: 6,
    interactions: ["navigation", "recovery"],
    realWorldActions: ["詳細を開く", "一覧へ戻る", "ホームへ戻る", "履歴から開き直す"],
    commonConcepts: ["現在地", "一つ前", "ホーム", "履歴", "作業は残る"],
    environmentOperations: environmentOperations(
      [["アプリ内の戻るで一覧へ戻る", "デスクトップを表示する", "ブラウザ履歴から詳細を開く"], "Alt+左はブラウザの戻るとして使えます。"],
      [["アプリ内の戻るで一覧へ戻る", "デスクトップを表示する", "履歴から詳細を開く"], "Command+[は対応アプリだけで使える補助操作です。"],
      [["左上または画面端の戻るを使う", "ホームへ戻る", "履歴から詳細を開く"], "戻るジェスチャーが使えない画面もあります。"],
      [["戻るジェスチャーまたはボタンを使う", "ホームへ戻る", "履歴から詳細を開く"], "システムの戻るとアプリ上部の戻るは同じ結果になる場合があります。"],
    ),
    hints: progressiveHints(
      "帰りたい場所が『直前』『起点』『前に見たページ』のどれか考えましょう。",
      "一覧へは戻る、端末の起点へはホーム、前のページへは履歴です。",
      "上部の戻るで一覧へ戻り、デスクトップを表示し、ブラウザ履歴から開き直します。",
      "上部の戻るで一覧へ戻り、デスクトップを表示し、履歴から開き直します。",
      "左上の戻る、ホーム操作、ブラウザ履歴の順に使います。",
      "戻る、ホーム、ブラウザ履歴の順に使います。",
    ),
    afterCompletion: "一つ前とホームを区別し、履歴から作業へ戻れます。",
    xp: 40,
    danger: danger("green", "見る場所を移るだけです。入力した内容は消えません。"),
    success: missionSuccess(
      "一覧、ホーム、履歴からの再表示をすべて体験している。",
      [
        ["listView", "お知らせ一覧へ戻っている"],
        ["homeState", "端末の起点へ戻っている"],
        ["historyReopen", "履歴から同じ詳細を開き直している"],
      ],
      [["navigationChoiceExplained", "explanation", "戻る先の違いを説明できた"]],
    ),
  },
  {
    id: "open-close",
    areaId: "navigate-screens",
    order: 6,
    title: "開く・閉じる・残す",
    mission: "途中のメモを残したまま、別の画面へ移りましょう。",
    objective: "開く、隠す、閉じる、終了する違いを知る。",
    competency: "アプリと作業内容がどの状態で残るかを観察する。",
    competencyIds: ["C2", "C6"],
    prerequisites: ["navigation"],
    transferTo: ["app-switch", "typing", "account-recovery"],
    guidance: "show",
    estimatedMinutes: 6,
    interactions: ["open-close", "navigation", "typing"],
    realWorldActions: ["メモを開く", "途中まで入力する", "一時的に離れる", "再表示する", "閉じる"],
    commonConcepts: ["ウィンドウ", "アプリ", "最小化", "バックグラウンド", "終了"],
    environmentOperations: environmentOperations(
      [["メモを最小化する", "タスクバーから再表示する", "閉じるボタンで閉じる"], "閉じると終了が同じかはアプリで異なります。"],
      [["黄色でしまう", "Dockから再表示する", "赤でウィンドウを閉じる"], "赤で閉じてもアプリが動き続ける場合があります。"],
      [["ホームへ戻る", "アプリスイッチャーからメモへ戻る"], "上へ払う強制終了は普段の終了方法ではありません。"],
      [["ホームへ戻る", "履歴画面からメモへ戻る"], "設定の強制停止は普段の操作ではありません。"],
    ),
    hints: progressiveHints(
      "メモを消さずに、いったん見えない所へ移せます。",
      "最小化またはホームを使い、同じアプリをもう一度開きます。",
      "最小化し、タスクバーのメモを選んで戻ります。",
      "黄色のボタンでしまい、Dockのメモを選んで戻ります。",
      "ホームへ戻り、アプリスイッチャーからメモを選びます。",
      "ホームへ戻り、履歴画面からメモを選びます。",
    ),
    afterCompletion: "画面から消えても、作業が残っている場合を見分けられます。",
    xp: 40,
    danger: danger("yellow", "閉じる前に、途中の内容が保存されているか確認します。"),
    success: missionSuccess(
      "途中のメモが保持されたまま再表示され、最後に指定状態で閉じている。",
      [
        ["draftText", "途中まで入力した文が残っている"],
        ["draftReopened", "離れた後に同じ文を再表示している"],
        ["targetAppState", "最後にアプリが指定の閉じた状態になっている"],
      ],
      [["closeVsQuitObserved", "observation", "閉じると終了の違いを確認した"]],
    ),
  },
  {
    id: "app-switch",
    areaId: "navigate-screens",
    order: 7,
    title: "二つの画面を行き来する",
    mission: "予定を見ながら、日時をメモへ残しましょう。",
    objective: "二つのアプリを切り替え、一方の情報を他方で使う。",
    competency: "画面が消えたと考えず、アプリやウィンドウを再び前へ出す。",
    competencyIds: ["C2", "C7"],
    prerequisites: ["open-close"],
    transferTo: ["copy-paste", "tabs-compare", "account-recovery", "attach-review"],
    guidance: "coach",
    estimatedMinutes: 6,
    interactions: ["app-switch", "typing", "navigation"],
    realWorldActions: ["予定を確認する", "メモへ切り替える", "日時を書く", "必要なら往復する"],
    commonConcepts: ["前にあるアプリ", "背景のアプリ", "切り替え", "内容の保持"],
    environmentOperations: environmentOperations(
      [["予定を開く", "Alt+Tabまたはタスクバーでメモへ切り替える", "日時を書く"], "ウィンドウは前後に重なります。"],
      [["予定を開く", "Command+TabまたはDockでメモへ切り替える", "日時を書く"], "Mission Controlでもウィンドウを選べます。"],
      [["予定を開く", "下端から上へ動かして止め、メモを選ぶ", "日時を書く"], "Homeボタン型では二度押しで切替画面を出します。"],
      [["予定を開く", "下端スワイプまたは履歴ボタンでメモを選ぶ", "日時を書く"], "ナビゲーション方式は端末設定で変わります。"],
    ),
    hints: progressiveHints(
      "予定を閉じなくても、メモを前へ出せます。",
      "アプリの切り替え画面か、いつもアプリを選ぶ場所を使います。",
      "Alt+Tabを押し、メモが選ばれたらキーを離します。",
      "Command+Tabを押し、メモが選ばれたらキーを離します。",
      "下端から上へ動かして止め、メモのカードをタップします。",
      "履歴画面を開き、メモのカードをタップします。",
    ),
    afterCompletion: "二つのアプリを何度でも往復して、情報を使えます。",
    xp: 45,
    danger: danger("green", "切り替えても予定やメモは消えません。"),
    success: missionSuccess(
      "予定を確認した後、メモへ正しい日時を残している。",
      [
        ["calendarViewed", "対象の予定を確認している"],
        ["noteContainsTarget", "メモに対象日時が含まれている"],
      ],
      [["appSwitchUsed", "interaction", "アプリ間を一度以上切り替えた"]],
    ),
  },
  {
    id: "menu-discovery",
    areaId: "navigate-screens",
    order: 8,
    title: "メニューを手掛かりから探す",
    mission: "記事を読みやすくし、共有の場所だけ確認しましょう。",
    objective: "記号や配置を手掛かりに、隠れた機能を安全に探す。",
    competency: "三点、三本線、歯車、プロフィール、メニューバーを推測する。",
    competencyIds: ["C2", "C5", "C7"],
    prerequisites: ["context", "navigation", "open-close"],
    transferTo: ["permission-decision", "wifi-recovery", "independent-settings"],
    guidance: "challenge",
    estimatedMinutes: 7,
    interactions: ["menu-discovery", "context-menu", "navigation"],
    realWorldActions: ["画面の手掛かりを探す", "候補メニューを開く", "文字を大きくする", "共有は確定しない"],
    commonConcepts: ["三点", "歯車", "共有", "設定", "配置は変わる"],
    environmentOperations: environmentOperations(
      [["三点、歯車、三本線を順に確認する", "表示設定で文字を大きくする", "共有パネルは見るだけで閉じる"], "Startや右クリックも機能の入口になります。"],
      [["画面上部のメニューバーとアプリ内メニューを確認する", "文字を大きくする", "共有は閉じる"], "Macの共通メニューバーはウィンドウの外にあります。"],
      [["三点、共有、プロフィールを確認する", "文字サイズを変える", "共有先を選ばず閉じる"], "一部の設定は設定アプリ側にあります。"],
      [["縦三点、三本線、プロフィールを確認する", "文字サイズを変える", "共有先を選ばず閉じる"], "配置はメーカーやアプリ版で変わります。"],
    ),
    hints: progressiveHints(
      "画面の端にある、説明のない小さな印を安全に見てみましょう。",
      "三点、歯車、共有の印が手掛かりです。",
      "右上の三点から表示設定を開き、共有パネルは確定せず閉じます。",
      "画面上部の表示メニューを開き、共有パネルは確定せず閉じます。",
      "三点から表示を変え、共有の印は開いた後に閉じます。",
      "縦三点から表示を変え、共有の印は開いた後に閉じます。",
    ),
    afterCompletion: "見本と場所が違っても、記号から機能を探せます。",
    xp: 50,
    danger: danger("yellow", "メニューを見るのは安全です。共有先の確定はまだ行いません。"),
    success: missionSuccess(
      "文字サイズが指定値で、共有パネルを確認後も送信していない。",
      [
        ["textSize", "記事の文字サイズが指定値になっている"],
        ["sharePanelViewed", "共有パネルを一度確認している"],
        ["shareNotCommitted", "共有は確定されていない"],
      ],
      [["menuLandmarksCompared", "observation", "複数のメニュー手掛かりを確認した"]],
    ),
  },
  {
    id: "typing",
    areaId: "work-with-text",
    order: 9,
    title: "必要な文字を入力する",
    mission: "日時と場所を入力し、変換まちがいを直しましょう。",
    objective: "入力欄を選び、日本語、数字、記号を正しく入力する。",
    competency: "フォーカス、文字種、変換、確定、削除を使い分ける。",
    competencyIds: ["C1"],
    prerequisites: ["pointer"],
    transferTo: ["text-selection", "browser-search", "form-review"],
    guidance: "show",
    estimatedMinutes: 7,
    interactions: ["typing", "pointer"],
    realWorldActions: ["入力欄を選ぶ", "日本語を変換する", "数字と記号を入れる", "一部だけ直す"],
    commonConcepts: ["入力位置", "文字種", "変換候補", "確定", "個人情報を使わない"],
    environmentOperations: environmentOperations(
      [["半角／全角で日本語入力へ切り替える", "Spaceで変換しEnterで確定する", "Backspaceで誤字だけ消す"], "Deleteはカーソルの後ろ、Backspaceは前を消します。"],
      [["日本語入力へ切り替える", "Spaceで変換しReturnで確定する", "Deleteで誤字だけ消す"], "Windowsと修飾キーやキー名が異なります。"],
      [["かなまたはローマ字キーボードを選ぶ", "数字・記号画面へ切り替える", "候補を選び完了する"], "キーボードの種類は設定で変えられます。"],
      [["Gboard等で12キーまたはQWERTYを使う", "数字・記号へ切り替える", "候補を選び確定する"], "キーボードの見た目は機種で異なります。"],
    ),
    hints: progressiveHints(
      "文字が入る場所を先に選び、入力位置を確認しましょう。",
      "日本語、数字、記号はキーボードの表示を切り替えて入れます。",
      "欄をクリックし、日本語入力で『中央公民館』、数字で『7月21日 10:30』と入力します。",
      "欄をクリックし、日本語入力で場所、数字で日時を入力してReturnで確定します。",
      "欄をタップし、文字と数字の画面を切り替えて場所と日時を入力します。",
      "欄をタップし、Gboardの文字と数字を切り替えて場所と日時を入力します。",
    ),
    afterCompletion: "誤入力を全部消さず、必要な所だけ直して入力できます。",
    xp: 45,
    danger: danger("yellow", "練習用の日時と場所だけを入力し、本物の個人情報は使いません。"),
    success: missionSuccess(
      "正規化後の日時と場所が目標値に一致している。入力方式は問わない。",
      [
        ["dateTimeValue", "日時が『7月21日 10:30』になっている"],
        ["placeValue", "場所が『中央公民館』になっている"],
      ],
      [
        ["fieldFocused", "interaction", "入力欄を自分で選んだ"],
        ["mistakeCorrected", "recovery", "誤入力を部分的に修正した"],
      ],
    ),
  },
  {
    id: "text-selection",
    areaId: "work-with-text",
    order: 10,
    title: "必要な部分だけ選ぶ",
    mission: "案内から『受付番号 A-204』だけを選びましょう。",
    objective: "文全体ではなく、必要な語句だけを選択する。",
    competency: "ドラッグ、単語選択、選択ハンドルで範囲を調整する。",
    competencyIds: ["C1"],
    prerequisites: ["pointer", "typing"],
    transferTo: ["copy-paste", "search-refine", "alternate-solution"],
    guidance: "coach",
    estimatedMinutes: 6,
    interactions: ["text-selection", "pointer"],
    realWorldActions: ["選択を始める", "範囲を広げる", "範囲を狭める", "選択結果を読む"],
    commonConcepts: ["文字範囲", "選択表示", "始点と終点", "選択解除"],
    environmentOperations: environmentOperations(
      [["文字の始めから終わりまでドラッグする", "必要なら単語をダブルクリックする", "範囲を調整する"], "Shiftを使った範囲選択もあります。"],
      [["文字の始めから終わりまでドラッグする", "必要なら単語をダブルクリックする", "範囲を調整する"], "トラックパッドでは押したまま指を動かします。"],
      [["語句をダブルタップする", "選択ハンドルを両端へ動かす"], "長押しで入力位置を動かす操作とは別です。"],
      [["語句を長押しまたはダブルタップする", "選択ハンドルを動かす"], "選択ツールバーの見た目はアプリで変わります。"],
    ),
    hints: progressiveHints(
      "必要な文字の始まりと終わりを見つけましょう。",
      "『受付番号』から『A-204』までを選択表示にします。",
      "『受』から『4』までポインターを押したままドラッグします。",
      "『受』から『4』までトラックパッドを押したまま動かします。",
      "『受付番号』をダブルタップし、ハンドルを『A-204』の後ろまで動かします。",
      "『受付番号』を長押しし、ハンドルを『A-204』の後ろまで動かします。",
    ),
    afterCompletion: "必要な部分だけを目で確認しながら選べます。",
    xp: 45,
    danger: danger("green", "選択するだけでは元の文章は変わりません。"),
    success: missionSuccess(
      "選択中の文字が『受付番号 A-204』と一致している。",
      [["selectedText", "必要な語句だけが選択されている"]],
      [
        ["selectionRangeInspected", "observation", "選択範囲を確認した"],
        ["selectionAdjusted", "recovery", "過不足のある選択を調整した", false],
      ],
    ),
  },
  {
    id: "copy-paste",
    areaId: "work-with-text",
    order: 11,
    title: "内容を別の場所で使う",
    mission: "受付番号をコピーし、申込メモへ貼り付けましょう。",
    objective: "選択した内容を、別のアプリの正しい位置へ移す。",
    competency: "クリップボード、コピー、貼り付け、切り取りの違いを知る。",
    competencyIds: ["C1", "C2"],
    prerequisites: ["text-selection", "app-switch"],
    transferTo: ["edit-undo", "attach-review", "alternate-solution"],
    guidance: "coach",
    estimatedMinutes: 7,
    interactions: ["copy-paste", "text-selection", "app-switch", "context-menu"],
    realWorldActions: ["文字を選ぶ", "実環境の操作でコピーする", "アプリを切り替える", "入力位置へ貼り付ける"],
    commonConcepts: ["クリップボード", "元は残る", "入力位置", "コピーと切り取り"],
    environmentOperations: environmentOperations(
      [["受付番号を選ぶ", "Ctrl+Cまたは右クリックでコピーする", "メモでCtrl+Vまたは右クリックして貼り付ける"], "ショートカットとメニューのどちらも同じ結果になります。"],
      [["受付番号を選ぶ", "Command+CまたはControlクリックでコピーする", "メモでCommand+Vする"], "画面上部の編集メニューも使えます。"],
      [["受付番号を選び『コピー』をタップする", "メモへ切り替える", "入力欄を長押しして『ペースト』する"], "編集メニューが横へ続く場合があります。"],
      [["受付番号を選びツールバーの『コピー』を使う", "メモへ切り替える", "入力欄を長押しして貼り付ける"], "Gboardのクリップボードは別の選択肢です。"],
    ),
    hints: progressiveHints(
      "元の文を残したまま、同じ内容を別の場所へ渡せます。",
      "先に文字を選んでコピーし、メモの入力位置で貼り付けます。",
      "選択後Ctrl+C、メモへ切り替え、入力欄でCtrl+Vを使います。",
      "選択後Command+C、メモへ切り替え、入力欄でCommand+Vを使います。",
      "選択メニューのコピーを使い、メモ欄を長押ししてペーストします。",
      "選択ツールバーのコピーを使い、メモ欄を長押しして貼り付けます。",
    ),
    afterCompletion: "本物に近い操作で、元を消さず別の場所へ内容を移せます。",
    xp: 50,
    danger: danger("green", "コピーでは元の文章は消えません。貼り付け先だけ確認します。"),
    success: missionSuccess(
      "元の文章が残り、メモに受付番号が含まれている。経路は問わない。",
      [
        ["sourceText", "元の案内文が保持されている"],
        ["destinationValue", "申込メモに『受付番号 A-204』が含まれている"],
      ],
      [
        ["nativeCopyRouteUsed", "interaction", "環境固有のコピー操作を使った"],
        ["appSwitchDuringCopy", "interaction", "別のアプリへ切り替えた"],
      ],
    ),
  },
  {
    id: "edit-undo",
    areaId: "work-with-text",
    order: 12,
    title: "書き直して元に戻す",
    mission: "時刻を直し、取り消しとやり直しを試しましょう。",
    objective: "文の一部だけを編集し、編集履歴を前後に動かす。",
    competency: "カーソル、部分削除、画面上の取り消し・やり直しを扱う。",
    competencyIds: ["C1", "C6"],
    prerequisites: ["typing", "text-selection", "copy-paste", "recovery"],
    transferTo: ["form-review", "error-reading", "independent-settings"],
    guidance: "challenge",
    estimatedMinutes: 7,
    interactions: ["edit-undo", "typing", "text-selection", "recovery"],
    realWorldActions: ["時刻だけを選ぶ", "10:30へ直す", "取り消して旧時刻を見る", "やり直して新時刻へ戻す"],
    commonConcepts: ["部分編集", "取り消し", "やり直し", "編集履歴", "保存"],
    environmentOperations: environmentOperations(
      [["10:00だけを10:30へ直す", "画面上の『取り消し』を左クリックする", "画面上の『やり直し』を左クリックする"], "保存前後で戻せる範囲はアプリにより異なります。"],
      [["10:00だけを10:30へ直す", "画面上の『取り消す』をクリックする", "画面上の『やり直す』をクリックする"], "画面上のボタンを使って練習します。"],
      [["時刻だけを選んで直す", "画面上の『取り消す』をタップする", "画面上の『やり直す』をタップする"], "ボタンの位置はアプリによって異なります。"],
      [["時刻だけを選んで直す", "画面上の『取り消す』をタップする", "画面上の『やり直す』をタップする"], "ボタンの位置はアプリによって異なります。"],
    ),
    hints: progressiveHints(
      "全文ではなく、変えたい時刻だけに注目しましょう。",
      "新しい時刻へ直した後、『取り消し』と『やり直し』を一度ずつ使います。",
      "10:00を10:30へ直し、画面上の『取り消し』『やり直し』を順に左クリックします。",
      "10:00を10:30へ直し、画面上の『取り消す』『やり直す』を順にクリックします。",
      "10:00を10:30へ直し、画面上の『取り消す』『やり直す』を順にタップします。",
      "10:00を10:30へ直し、画面上の『取り消す』『やり直す』を順にタップします。",
    ),
    afterCompletion: "全部を書き直さず、編集を一つ戻してもう一度進められます。",
    xp: 55,
    danger: danger("yellow", "編集内容が変わります。取り消しで戻せる範囲を確認しながら進めます。"),
    success: missionSuccess(
      "『取り消し』で旧時刻を確認後、『やり直し』で新時刻へ戻っている。",
      [["noteTimeValue", "最終時刻が10:30になっている"]],
      [
        ["oldValueObservedAfterUndo", "recovery", "取り消し後に10:00を確認した"],
        ["newValueRestoredAfterRedo", "recovery", "やり直し後に10:30を確認した"],
      ],
    ),
  },
  {
    id: "browser-search",
    areaId: "find-and-check",
    order: 13,
    title: "ブラウザで目的地を探す",
    mission: "市民センターの休館日を探しましょう。",
    objective: "ブラウザ、検索欄、結果、リンクを区別して目的ページへ進む。",
    competency: "検索語を入力し、個人情報を使わず必要なページへ到達する。",
    competencyIds: ["C2", "C3"],
    prerequisites: ["typing", "navigation"],
    transferTo: ["search-refine", "download-locate", "wifi-recovery"],
    guidance: "coach",
    estimatedMinutes: 7,
    interactions: ["browser-search", "typing", "navigation"],
    realWorldActions: ["ブラウザを開く", "検索欄へ語を入れる", "結果を読む", "公式案内を開く"],
    commonConcepts: ["ブラウザ", "検索エンジン", "検索欄", "URL", "リンク"],
    environmentOperations: environmentOperations(
      [["Edge風ブラウザを開く", "上部欄へ検索語を入れる", "公式案内リンクを開く"], "既定ブラウザは別の物へ変更できます。"],
      [["Safari風ブラウザを開く", "スマート検索欄へ語を入れる", "公式案内を開く"], "Windowsとショートカットの修飾キーが異なります。"],
      [["Safari風ブラウザを開く", "上部または下部の検索欄へ語を入れる", "公式案内を開く"], "検索欄の位置は設定で変わる場合があります。"],
      [["Chrome風ブラウザを開く", "上部検索欄へ語を入れる", "公式案内を開く"], "メーカーの別ブラウザが既定の場合もあります。"],
    ),
    hints: progressiveHints(
      "施設名、地域、知りたいことを短く組み合わせましょう。",
      "検索欄へ『さくら市 市民センター 休館日』と入れ、発信元を見ます。",
      "Edge風ブラウザの上部欄で検索し、『さくら市公式』の結果を開きます。",
      "Safari風ブラウザの検索欄で検索し、『さくら市公式』を開きます。",
      "Safari風ブラウザの検索欄で検索し、『さくら市公式』をタップします。",
      "Chrome風ブラウザの検索欄で検索し、『さくら市公式』をタップします。",
    ),
    afterCompletion: "ブラウザと検索結果を見分け、必要なページへ進めます。",
    xp: 50,
    danger: danger("yellow", "検索欄へ本物の氏名、住所、電話番号は入れません。"),
    success: missionSuccess(
      "合理的な検索語で、さくら市の公式休館日ページを開いている。",
      [["targetPageOpened", "公式の休館日ページが開いている"]],
      [
        ["browserOpened", "interaction", "ブラウザを自分で開いた"],
        ["querySubmitted", "interaction", "目的に合う検索語を送信した"],
      ],
    ),
  },
  {
    id: "search-refine",
    areaId: "find-and-check",
    order: 14,
    title: "検索語を変えて絞る",
    mission: "あいまいな検索を直し、目的の施設を見つけましょう。",
    objective: "結果が違うとき、語を追加、削除、置換して改善する。",
    competency: "場所、固有名詞、目的語を使い、検索結果の変化を観察する。",
    competencyIds: ["C3", "C6"],
    prerequisites: ["browser-search"],
    transferTo: ["tabs-compare", "help-search", "independent-research"],
    guidance: "coach",
    estimatedMinutes: 7,
    interactions: ["search-refine", "browser-search", "typing", "text-selection"],
    realWorldActions: ["最初の結果を見る", "検索欄を編集する", "地域名と施設名を足す", "結果の改善を見る"],
    commonConcepts: ["検索語", "固有名詞", "場所", "検索候補", "検索はやり直せる"],
    environmentOperations: environmentOperations(
      [["検索欄をCtrl+Aで選ぶ", "『さくら市 中央公民館 開館時間』へ直す", "結果を再確認する"], "全文選択だけでなく一部だけ直しても構いません。"],
      [["検索欄をCommand+Aで選ぶ", "地域名と施設名を足す", "結果を再確認する"], "CommandがWindowsのCtrlに近い役割です。"],
      [["検索欄をタップして編集する", "地域名と施設名を足す", "キーボードの検索を使う"], "全選択と部分編集のどちらも使えます。"],
      [["検索欄をタップして編集する", "地域名と施設名を足す", "Gboardの検索を使う"], "音声入力も代替手段として使えます。"],
    ),
    hints: progressiveHints(
      "今の検索語に、場所や正式な名前を足せないか考えましょう。",
      "『さくら市』『中央公民館』『開館時間』の三つが手掛かりです。",
      "検索欄をCtrl+Aで選び、『さくら市 中央公民館 開館時間』へ直します。",
      "検索欄をCommand+Aで選び、『さくら市 中央公民館 開館時間』へ直します。",
      "検索欄をタップして地域名と正式名を足し、もう一度検索します。",
      "検索欄をタップして地域名と正式名を足し、もう一度検索します。",
    ),
    afterCompletion: "最初の検索で見つからなくても、言葉を直して近づけます。",
    xp: 55,
    danger: danger("green", "検索語は何度でも直せます。結果が違っても失敗ではありません。"),
    success: missionSuccess(
      "検索語を一度以上改善し、対象施設の結果を表示している。",
      [["targetResultVisible", "対象施設の開館時間結果が表示されている"]],
      [
        ["queryRevisionCount", "recovery", "検索語を一度以上改善した"],
        ["resultChangeObserved", "observation", "検索結果の変化を確認した"],
      ],
    ),
  },
  {
    id: "tabs-compare",
    areaId: "find-and-check",
    order: 15,
    title: "二つの情報を比べる",
    mission: "今年と前年の案内を比べ、今の時間を選びましょう。",
    objective: "複数ページを保持して行き来し、日付と内容を比較する。",
    competency: "タブ、履歴、別画面を使い、比較する軸をそろえる。",
    competencyIds: ["C2", "C3"],
    prerequisites: ["app-switch", "browser-search", "search-refine"],
    transferTo: ["source-check", "independent-research"],
    guidance: "challenge",
    estimatedMinutes: 8,
    interactions: ["tabs-compare", "app-switch", "browser-search", "navigation"],
    realWorldActions: ["今年の案内を開く", "前年の記事を別に開く", "日付を見る", "現在の答えを選ぶ"],
    commonConcepts: ["タブ", "複数ページ", "比較軸", "掲載日", "古い情報"],
    environmentOperations: environmentOperations(
      [["結果を新しいタブで開く", "Ctrl+Tabで切り替える", "日付と時間を比べる"], "別ウィンドウや履歴でも比較できます。"],
      [["二つをタブで開く", "Control+Tabまたはタブ概要で切り替える", "日付を比べる"], "Command+Tabはアプリ切替なので区別します。"],
      [["二つをタブで開く", "タブ一覧から交互に見る", "日付と時間を比べる"], "一画面に一ページでも保持して比べられます。"],
      [["二つをタブで開く", "タブ数ボタンまたはスワイプで切り替える", "日付を比べる"], "タブの配置はブラウザ版で変わります。"],
    ),
    hints: progressiveHints(
      "内容だけでなく、いつ、誰が出した情報かも並べて見ましょう。",
      "今年の公式案内と前年の記事を、閉じずに行き来します。",
      "二つを別タブで開き、Ctrl+Tabで日付と開館時間を比べます。",
      "二つを別タブで開き、タブ概要で日付と開館時間を比べます。",
      "タブボタンから二つを交互に開き、掲載日と時間を比べます。",
      "タブ一覧から二つを交互に開き、掲載日と時間を比べます。",
    ),
    afterCompletion: "一つ目だけで決めず、複数の情報を同じ軸で比べられます。",
    xp: 60,
    danger: danger("yellow", "古い案内を現在の情報と取り違えないよう、日付を確認します。"),
    success: missionSuccess(
      "両方の情報を確認し、今年の時間を選んでいる。開き方は問わない。",
      [["currentAnswerSelected", "現在の正しい開館時間が選ばれている"]],
      [
        ["bothSourcesOpened", "comparison", "二つの情報を開いた"],
        ["comparisonFieldsViewed", "comparison", "日付と時間を両方見比べた"],
      ],
    ),
  },
  {
    id: "source-check",
    areaId: "find-and-check",
    order: 16,
    title: "この情報は信じてよい？",
    mission: "四つの案内を、使う・参考・保留に分けましょう。",
    objective: "発信元、URL、日付、根拠から利用してよい情報か判断する。",
    competency: "公式性、新しさ、広告、誤情報を複数の根拠で確かめる。",
    competencyIds: ["C3", "C5"],
    prerequisites: ["browser-search", "search-refine", "tabs-compare"],
    transferTo: ["download-locate", "permission-decision", "suspicious-message", "help-search"],
    guidance: "challenge",
    estimatedMinutes: 9,
    interactions: ["source-check", "tabs-compare", "browser-search"],
    realWorldActions: ["発信元を見る", "URLを確認する", "日付を見る", "広告表示を見る", "判断を保留する"],
    commonConcepts: ["公式", "URL", "発信元", "更新日", "広告", "保留"],
    environmentOperations: environmentOperations(
      [["アドレス欄のドメインを見る", "広告ラベルと日付を確認する", "四件を分類する"], "鍵アイコンだけで内容の正しさは決まりません。"],
      [["簡略表示されたURLの詳細を見る", "発信者と日付を確認する", "四件を分類する"], "表示を展開して元のドメインを確かめます。"],
      [["省略URLを展開する", "共有元でなく元ページを見る", "発信元と日付で分類する"], "狭い画面では大事な情報が省略されます。"],
      [["サイト情報を開く", "スポンサー表示と元ページを確認する", "四件を分類する"], "アプリ内ブラウザと通常ブラウザを区別します。"],
    ),
    hints: progressiveHints(
      "『誰が』『いつ』『どこで』出した情報かを見ましょう。",
      "発信元、URL、日付、広告表示を一件ずつ確かめます。",
      "アドレス欄と掲載日を確認し、公式は利用、古い個人記事は参考、出典不明は保留にします。",
      "URL詳細と掲載日を確認し、公式は利用、古い記事は参考、出典不明は保留にします。",
      "URLを展開し、元ページと日付を確認して利用・参考・保留へ分けます。",
      "サイト情報と日付を確認し、利用・参考・保留へ分けます。",
    ),
    afterCompletion: "検索上位や鍵だけで決めず、分からない情報を保留できます。",
    xp: 65,
    danger: danger("yellow", "情報を使う前に根拠を確認し、判断できないときは保留します。"),
    success: missionSuccess(
      "四つの情報を安全基準に沿って分類し、理由を示している。",
      [["sourceClassifications", "四情報の分類が安全基準と一致している"]],
      [
        ["sourceSignalsViewed", "comparison", "発信元、日付、URLを確認した"],
        ["classificationReason", "explanation", "一件以上の判断理由を説明した"],
      ],
    ),
  },
  {
    id: "file-concepts",
    areaId: "files-and-photos",
    order: 17,
    title: "保存場所の地図をつかむ",
    mission: "資料と写真を、正しい保存場所へ分けましょう。",
    objective: "ファイル、フォルダ、写真、端末、クラウドの関係を区別する。",
    competency: "階層、現在地、端末内とクラウドの違いを画面から読む。",
    competencyIds: ["C2", "C4"],
    prerequisites: ["navigation", "open-close"],
    transferTo: ["file-organize", "download-locate", "independent-file"],
    guidance: "show",
    estimatedMinutes: 7,
    interactions: ["file-concepts", "navigation", "pointer"],
    realWorldActions: ["保存場所を分類する", "ファイル画面を開く", "現在地表示を見る", "写真との入口の違いを見る"],
    commonConcepts: ["ファイル", "フォルダ", "端末内", "クラウド", "写真", "ダウンロード"],
    environmentOperations: environmentOperations(
      [["File Explorerを開く", "This PC、Downloads、Documents、OneDriveを見る", "パンくずで現在地を読む"], "OneDriveはクラウドの保存場所です。"],
      [["Finderを開く", "Downloads、Documents、iCloud Driveを見る", "サイドバーで場所を読む"], "iCloud DriveとMac内は別の保存場所です。"],
      [["Filesを開く", "このiPhone内とiCloud Driveを見る", "Photosとの入口の違いを見る"], "写真と一般ファイルは別アプリに分かれやすいです。"],
      [["Files系アプリを開く", "Downloads、Images、端末、クラウドを見る", "場所の見出しを読む"], "アプリ名はメーカーで異なります。"],
    ),
    hints: progressiveHints(
      "『どのアプリか』だけでなく、『どこに保存されているか』を見ましょう。",
      "端末内、クラウド、写真、ダウンロードの四つへ分けます。",
      "File Explorerの左側と上部のパンくずを見て、資料をDownloads、写真をPicturesへ分けます。",
      "Finderのサイドバーを見て、資料をDownloads、写真をPicturesへ分けます。",
      "Filesの『このiPhone内』『iCloud Drive』とPhotosを見分けます。",
      "Files系アプリのDownloads、Images、クラウドを見分けます。",
    ),
    afterCompletion: "アプリ名だけでなく、データがある場所を説明できます。",
    xp: 50,
    danger: danger("green", "最初は分類と確認だけです。実際のファイルはまだ動かしません。"),
    success: missionSuccess(
      "保存場所の分類が基準を満たし、実画面の現在地を確認している。",
      [["locationClassification", "架空データが正しい場所へ分類されている"]],
      [
        ["locationHeaderViewed", "observation", "現在地の見出しまたはパンくずを確認した"],
        ["localVsCloudExplained", "explanation", "端末内とクラウドの違いを選べた"],
      ],
    ),
  },
  {
    id: "file-organize",
    areaId: "files-and-photos",
    order: 18,
    title: "名前を付けて整理する",
    mission: "資料へ分かる名前を付け、参加資料へ移しましょう。",
    objective: "フォルダを作り、名称を変え、正しい場所へ移動する。",
    competency: "作成、名称変更、移動、コピー、並び替え、復旧を使う。",
    competencyIds: ["C4", "C6"],
    prerequisites: ["file-concepts", "context", "typing", "recovery"],
    transferTo: ["download-locate", "attach-review", "independent-file"],
    guidance: "coach",
    estimatedMinutes: 9,
    interactions: ["file-organize", "context-menu", "typing", "recovery"],
    realWorldActions: ["フォルダを作る", "ファイル名を変える", "移動する", "重複や誤移動を直す"],
    commonConcepts: ["意味のある名前", "移動", "コピー", "重複", "ゴミ箱"],
    environmentOperations: environmentOperations(
      [["参加資料フォルダを作る", "F2または右クリックで名前を変える", "ドラッグまたは切り取りで移動する"], "ドラッグ先により移動かコピーかが変わります。"],
      [["Finderで新規フォルダを作る", "Returnで名前を変える", "ドラッグで移動する"], "Optionを押したドラッグはコピーになります。"],
      [["Filesの三点または長押しでフォルダを作る", "名称変更し、移動を選ぶ"], "Photosのアルバム整理とは別です。"],
      [["Files系アプリの三点または長押しを使う", "名称変更し、移動する"], "保存提供元をまたぐとコピーになる場合があります。"],
    ),
    hints: progressiveHints(
      "後から見つける人が分かる名前と場所を考えましょう。",
      "『参加資料』を作り、document1.pdfを『2026夏祭り案内.pdf』へ変えます。",
      "新規フォルダを作り、F2で名前を変え、参加資料へドラッグします。",
      "Finderでフォルダを作り、Returnで名前を変え、参加資料へドラッグします。",
      "Filesの三点でフォルダを作り、長押しメニューから名称変更と移動を使います。",
      "Files系アプリの三点でフォルダを作り、長押しから名称変更と移動を使います。",
    ),
    afterCompletion: "後から見つけられる名前と場所で、資料を整理できます。",
    xp: 60,
    danger: danger("yellow", "移動後に元の場所と新しい場所を確認します。完全削除はしません。"),
    success: missionSuccess(
      "指定フォルダ、意味のある名前、正しい場所がそろっている。",
      [
        ["folderExists", "参加資料フォルダが存在する"],
        ["targetFilename", "対象名が2026夏祭り案内.pdfになっている"],
        ["targetLocation", "対象が参加資料内にある"],
      ],
      [
        ["moveResultInspected", "observation", "移動後の元と先を確認した"],
        ["duplicateRecovered", "recovery", "重複または誤移動を整理した", false],
      ],
    ),
  },
  {
    id: "download-locate",
    areaId: "files-and-photos",
    order: 19,
    title: "ダウンロードした資料を見つける",
    mission: "取得した参加案内を見つけ、正しい版を開きましょう。",
    objective: "完了表示、履歴、既定保存先から取得した資料を探す。",
    competency: "ダウンロード、保存先、日付、サイズ、重複を確認する。",
    competencyIds: ["C4", "C6"],
    prerequisites: ["browser-search", "file-concepts", "file-organize"],
    transferTo: ["attach-review", "error-reading", "independent-file"],
    guidance: "coach",
    estimatedMinutes: 8,
    interactions: ["download-locate", "browser-search", "file-concepts", "file-organize"],
    realWorldActions: ["資料を一度取得する", "完了表示を見る", "保存先を開く", "日付とサイズで選ぶ"],
    commonConcepts: ["ダウンロード", "保存完了", "Downloads", "重複", "更新日時"],
    environmentOperations: environmentOperations(
      [["ブラウザのダウンロード表示を見る", "File ExplorerのDownloadsを開く", "日付とサイズで選ぶ"], "タスクバー通知から開ける場合もあります。"],
      [["Safari風のダウンロード表示を見る", "DockまたはFinderのDownloadsを開く", "日付を比べる"], "DockのDownloadsは保存場所への入口です。"],
      [["Safari風のダウンロード表示を見る", "FilesのDownloadsを開く", "PDFと写真保存を区別する"], "『写真に保存』はFilesへの取得と別です。"],
      [["ブラウザ通知を見る", "DownloadsまたはFiles系アプリを開く", "日付とサイズを比べる"], "画像とPDFで分類先が変わる場合があります。"],
    ),
    hints: progressiveHints(
      "もう一度押す前に、完了した印と保存された場所を探しましょう。",
      "ブラウザのダウンロード表示か『Downloads』が手掛かりです。",
      "ブラウザ右上の取得一覧を開き、File ExplorerのDownloadsで最新の参加案内を開きます。",
      "Safari風の取得一覧を開き、FinderのDownloadsで最新の参加案内を開きます。",
      "Safari風の取得表示からFilesのDownloadsへ進み、最新のPDFを開きます。",
      "ブラウザ通知からDownloadsへ進み、最新のPDFを開きます。",
    ),
    afterCompletion: "繰り返し取得せず、完了表示と保存場所から資料を探せます。",
    xp: 60,
    danger: danger("yellow", "同名の古い資料と区別するため、日付とサイズを確認します。"),
    success: missionSuccess(
      "取得済みの参加案内から、正しい最新版を開いている。",
      [["correctFileOpened", "最新の参加案内.pdfが開かれている"]],
      [
        ["downloadCompleted", "interaction", "資料の取得が完了した"],
        ["downloadMetadataCompared", "comparison", "同名ファイルの日付とサイズを比べた"],
        ["duplicateDownloadRecovered", "recovery", "重複取得後に正しい版を選別した", false],
      ],
    ),
  },
  {
    id: "attach-review",
    areaId: "files-and-photos",
    order: 20,
    title: "正しい資料を添付して確認する",
    mission: "夏祭り案内を添付し、送る前の確認を終えましょう。",
    objective: "相手と目的に合うファイルを選び、確定前に内容を見直す。",
    competency: "選択、添付、プレビュー、削除、宛先レビューを行う。",
    competencyIds: ["C4", "C5", "C6"],
    prerequisites: ["file-organize", "download-locate", "app-switch", "source-check"],
    transferTo: ["form-review", "independent-file", "independent-troubleshoot"],
    guidance: "challenge",
    estimatedMinutes: 10,
    interactions: ["attach-review", "file-concepts", "app-switch", "recovery"],
    realWorldActions: ["宛先を確認する", "ファイル選択を開く", "正しい版を添付する", "添付をプレビューする", "誤添付を外す"],
    commonConcepts: ["添付", "ファイル選択", "版", "宛先", "送信前確認"],
    environmentOperations: environmentOperations(
      [["クリップを選ぶ", "ファイル選択で場所と版を確認する", "添付チップを開いてレビューする"], "添付をドラッグできるアプリもあります。"],
      [["メールの添付またはFinderからドラッグする", "プレビューを開く", "宛先と件名を確認する"], "Finder風選択画面でも場所を確認します。"],
      [["メールから写真またはファイルを追加する", "PhotosとFilesを選び分ける", "添付と宛先を確認する"], "共有シートからメールを選ぶ別経路もあります。"],
      [["クリップまたは共有シートを使う", "提供元と版を選ぶ", "添付と宛先を確認する"], "システムファイル選択の見た目は機種で異なります。"],
    ),
    hints: progressiveHints(
      "添付できたかより、『誰に』『何を』『どの版で』送るかを見ましょう。",
      "宛先、件名、添付名、プレビューの四つを確認します。",
      "クリップから参加資料を開き、2026版を添付して、宛先とプレビューを確認します。",
      "添付からFinder風画面を開き、2026版を選び、宛先とプレビューを確認します。",
      "追加からFilesを開き、2026版を選び、宛先と添付プレビューを確認します。",
      "クリップからFiles系画面を開き、2026版を選び、宛先と添付を確認します。",
    ),
    afterCompletion: "添付の成功だけでなく、正しい版と相手を確定前に確認できます。",
    xp: 70,
    danger: danger("red", "送信は確定操作です。宛先、件名、添付を確認するまで進めません。"),
    success: missionSuccess(
      "宛先、件名、添付が目標と一致し、レビューが完了している。",
      [
        ["recipient", "宛先が練習相手と一致している"],
        ["subject", "件名が指定内容と一致している"],
        ["attachmentId", "2026版の資料だけが添付されている"],
        ["reviewChecklistCompleted", "送信前確認が完了している"],
      ],
      [
        ["attachmentPreviewed", "observation", "添付内容をプレビューした"],
        ["wrongAttachmentRecovered", "recovery", "古い版を外して直した", false],
      ],
    ),
  },
  {
    id: "permission-decision",
    areaId: "proceed-safely",
    order: 21,
    title: "許可してよいか考える",
    mission: "三つの権限を、目的に合う範囲で選びましょう。",
    objective: "許可名だけでなく、今なぜ必要かを考えて判断する。",
    competency: "機能目的、必要性、提供範囲、後からの変更を確認する。",
    competencyIds: ["C5"],
    prerequisites: ["menu-discovery", "source-check"],
    transferTo: ["account-recovery", "error-reading", "independent-troubleshoot"],
    guidance: "coach",
    estimatedMinutes: 8,
    interactions: ["permission-decision", "menu-discovery"],
    realWorldActions: ["権限要求を読む", "アプリの目的と比べる", "必要最小限を選ぶ", "判断理由を選ぶ"],
    commonConcepts: ["権限", "今回のみ", "使用中のみ", "拒否", "後から変更"],
    environmentOperations: environmentOperations(
      [["アプリ権限の説明を読む", "地図の位置は使用中のみ許可する", "懐中電灯の連絡先は拒否する"], "UACは一般のアプリ権限とは別の確認です。"],
      [["プライバシーとセキュリティの説明を読む", "必要なカメラや位置だけ許可する", "不要な連絡先は拒否する"], "許可は後からアプリ別に変更できます。"],
      [["今回だけ、使用中、許可しないを目的で選ぶ", "不要な連絡先を拒否する"], "正確な選択肢はiOS版で変わります。"],
      [["今回のみ、使用中のみ、許可しないを目的で選ぶ", "不要な連絡先を拒否する"], "文言はOS版やメーカーで変わります。"],
    ),
    hints: progressiveHints(
      "『この機能に、今その情報が本当に必要か』を考えましょう。",
      "地図の位置、懐中電灯の連絡先、カメラの三つを目的と比べます。",
      "地図は使用中のみ許可、懐中電灯の連絡先は拒否、カメラは今回だけを選びます。",
      "地図は使用中のみ許可、不要な連絡先は拒否、カメラは必要な範囲だけ許可します。",
      "地図はAppの使用中、連絡先は許可しない、カメラは今回だけを選びます。",
      "地図はアプリ使用中、連絡先は許可しない、カメラは今回のみを選びます。",
    ),
    afterCompletion: "すべて許可・すべて拒否ではなく、目的に合う最小限を選べます。",
    xp: 60,
    danger: danger("yellow", "権限は提供する情報の範囲を変えます。目的を確認して選びます。"),
    success: missionSuccess(
      "三つの権限判断が必要最小限の原則と一致している。",
      [["scenarioDecisions", "権限ごとの選択が安全基準と一致している"]],
      [["decisionReason", "decision", "各判断の理由を目的から選べた"]],
    ),
  },
  {
    id: "account-recovery",
    areaId: "proceed-safely",
    order: 22,
    title: "ログインできないとき",
    mission: "公式の再設定から、練習アカウントへ戻りましょう。",
    objective: "パスワードを推測し続けず、公式の回復経路を使う。",
    competency: "再設定、認証コード、自動入力、多要素認証を安全に扱う。",
    competencyIds: ["C5", "C6"],
    prerequisites: ["typing", "app-switch", "source-check", "permission-decision"],
    transferTo: ["form-review", "suspicious-message", "independent-troubleshoot"],
    guidance: "challenge",
    estimatedMinutes: 10,
    interactions: ["account-recovery", "app-switch", "typing", "source-check"],
    realWorldActions: ["公式ページを確認する", "パスワードを忘れたを選ぶ", "練習メールへ切り替える", "コードを戻して入力する", "共有要求を断る"],
    commonConcepts: ["アカウント", "パスワード", "認証コード", "公式の再設定", "秘密情報"],
    environmentOperations: environmentOperations(
      [["ブラウザの公式ログインを確認する", "再設定を始める", "Alt+Tabでメールのコードを確認して戻る"], "パスワードマネージャー候補も安全な選択肢です。"],
      [["公式ログインを確認する", "再設定を始める", "Command+Tabでメールと往復する"], "パスワード自動入力を使える場合があります。"],
      [["アプリまたはSafariの公式画面から再設定する", "メールのコードを確認する", "誰にもコードを渡さない"], "コード候補が出ても送信先を確認します。"],
      [["アプリまたはChromeの公式画面から再設定する", "SMSまたはメールのコードを確認する", "コードを共有しない"], "自動入力の種類は端末で異なります。"],
    ),
    hints: progressiveHints(
      "何度も推測せず、公式画面にある回復の入口を探しましょう。",
      "『パスワードを忘れた』から始め、練習メールの認証コードを使います。",
      "公式URLを確認して再設定を開き、Alt+Tabでメールのコードを確認して戻ります。",
      "公式URLを確認して再設定を開き、Command+Tabでメールのコードを確認して戻ります。",
      "公式画面の再設定を開き、メールのコードを確認して元画面へ戻ります。",
      "公式画面の再設定を開き、メールまたはSMSのコードを確認して戻ります。",
    ),
    afterCompletion: "秘密を他人へ渡さず、公式経路でアカウントを回復できます。",
    xp: 70,
    danger: danger("red", "本物のパスワードや認証コードは入力・共有しません。練習用だけを使います。"),
    success: missionSuccess(
      "公式回復画面から練習コードを使い、共有要求を拒否している。",
      [
        ["officialRecoveryOpened", "公式の再設定画面を開いている"],
        ["codeEntered", "練習用認証コードが入力されている"],
        ["accountRecovered", "練習アカウントへ戻れている"],
      ],
      [
        ["codeRetrievedInSandbox", "interaction", "練習メールでコードを確認した"],
        ["secretSharingRejected", "decision", "コードの共有要求を拒否した"],
      ],
    ),
  },
  {
    id: "form-review",
    areaId: "proceed-safely",
    order: 23,
    title: "送信前に見直す",
    mission: "申込内容の誤りを直し、確認画面まで進みましょう。",
    objective: "必須項目と入力形式を確認し、内容を失わず修正する。",
    competency: "長いフォーム、エラー表示、確認画面、戻って修正を扱う。",
    competencyIds: ["C1", "C5", "C6"],
    prerequisites: ["typing", "edit-undo", "scroll", "source-check"],
    transferTo: ["suspicious-message", "error-reading", "independent-troubleshoot"],
    guidance: "challenge",
    estimatedMinutes: 10,
    interactions: ["form-review", "typing", "scroll", "edit-undo", "recovery"],
    realWorldActions: ["フォームを入力する", "確認画面を見る", "エラー項目を読む", "戻って直す", "最終内容を見直す"],
    commonConcepts: ["必須", "入力形式", "確認画面", "戻って修正", "送信前"],
    environmentOperations: environmentOperations(
      [["Tabで項目を移る", "ラジオ、チェック、リストを選ぶ", "確認から戻って人数を直す"], "ブラウザ自動入力の内容も確認します。"],
      [["Tabまたはポインターで項目を移る", "フォーム部品を選ぶ", "確認から戻って直す"], "Tab移動の設定により動きが異なります。"],
      [["項目ごとのキーボードを使う", "入力中に画面を動かす", "確認から戻って直す"], "キーボードの次へ・完了も使えます。"],
      [["Gboardの次へで項目を進む", "隠れた項目までスクロールする", "確認から戻って直す"], "キーボードで項目が隠れたら画面を動かします。"],
    ),
    hints: progressiveHints(
      "送信ボタンを見る前に、画面に示された問題の場所を探しましょう。",
      "人数の誤りと、未選択の連絡方法を確認画面から直します。",
      "確認画面の項目名を読み、『入力へ戻る』で人数と連絡方法を直します。",
      "確認画面の項目名を読み、戻って人数と連絡方法を直します。",
      "確認画面から入力へ戻り、人数と未選択項目を直してもう一度確認します。",
      "確認画面から入力へ戻り、人数と未選択項目を直してもう一度確認します。",
    ),
    afterCompletion: "入力を失わず戻って直し、確定前に全体を確認できます。",
    xp: 70,
    danger: danger("red", "送信は確定操作です。この練習では最終確認までで外部送信しません。"),
    success: missionSuccess(
      "すべてのエラーが解消され、確認画面の要約が目標と一致している。",
      [
        ["validationErrorsResolved", "入力エラーがすべて解消されている"],
        ["finalSummaryMatches", "確認画面が目標内容と一致している"],
      ],
      [
        ["reviewVisited", "observation", "確認画面を実際に見た"],
        ["correctionMade", "recovery", "入力を失わず戻って修正した"],
      ],
    ),
  },
  {
    id: "suspicious-message",
    areaId: "proceed-safely",
    order: 24,
    title: "怪しいメッセージで止まる",
    mission: "リンクを押さず、公式の入口から状態を確かめましょう。",
    objective: "急がせる要求の前で止まり、送信元と別経路を確認する。",
    competency: "フィッシング、偽SMS、偽警告、公式経路を見分ける。",
    competencyIds: ["C3", "C5"],
    prerequisites: ["source-check", "account-recovery", "form-review"],
    transferTo: ["help-search", "independent-research", "independent-troubleshoot"],
    guidance: "challenge",
    estimatedMinutes: 9,
    interactions: ["suspicious-message", "source-check", "navigation"],
    realWorldActions: ["要求内容を読む", "送信元を見る", "リンクを開かない", "公式アプリへ別経路で進む", "報告する"],
    commonConcepts: ["急がせる文", "送信元", "リンク先", "公式経路", "認証要求", "報告"],
    environmentOperations: environmentOperations(
      [["差出人詳細を見る", "リンクへポインターを置いて表示先を見る", "保存済み公式ページから確認して報告する"], "ホバー先だけで安全とは決めません。"],
      [["送信元詳細を見る", "リンク先表示を確認する", "公式アプリまたはブックマークから確認する"], "Controlクリックでリンクをコピーする方法は発展です。"],
      [["SMSの送信者と要求を読む", "リンクは長押しせず公式アプリへ移る", "メッセージを報告する"], "誤タップを避けるためリンクから離れて確認します。"],
      [["SMSまたは通知の送信元を見る", "リンクを開かず公式アプリへ移る", "迷惑報告する"], "通知上のボタンも慎重に扱います。"],
    ),
    hints: progressiveHints(
      "急がされても、メッセージ内の入口を使わず確認できます。",
      "送信元、期限の急かし、秘密情報の要求を見て、公式アプリへ別に移ります。",
      "リンクは押さず、差出人詳細を見て、ブックマークした公式ページから状態を確認します。",
      "リンクは押さず、送信元詳細を見て、公式アプリから状態を確認します。",
      "メッセージを閉じ、ホームから公式アプリを開いて状態を確認し、報告します。",
      "通知を閉じ、ホームから公式アプリを開いて状態を確認し、迷惑報告します。",
    ),
    afterCompletion: "急かされてもリンクを使わず、公式の入口から確かめられます。",
    xp: 75,
    danger: danger("red", "怪しいリンク、認証要求、秘密情報入力の前で必ず止まります。"),
    success: missionSuccess(
      "怪しいリンクを開かず、公式経路で状態を確認して報告している。",
      [
        ["suspiciousLinkNotOpened", "怪しいリンクが開かれていない"],
        ["officialRouteUsed", "保存済みの公式経路を使っている"],
        ["messageReported", "怪しいメッセージを報告している"],
      ],
      [["suspicionReasons", "decision", "怪しい理由を二つ以上選べた"]],
    ),
  },
  {
    id: "error-reading",
    areaId: "solve-problems",
    order: 25,
    title: "エラーを次の手掛かりにする",
    mission: "容量不足の案内を読み、写真を保存できる状態へ戻しましょう。",
    objective: "エラーから、できなかったことと次に確かめる物を読み取る。",
    competency: "入力、通信、権限、保存先の原因候補を分けて再試行する。",
    competencyIds: ["C6", "C7"],
    prerequisites: ["recovery", "form-review", "permission-decision"],
    transferTo: ["wifi-recovery", "help-search", "independent-troubleshoot"],
    guidance: "coach",
    estimatedMinutes: 9,
    interactions: ["error-reading", "recovery", "file-organize"],
    realWorldActions: ["エラーを閉じず読む", "原因を分類する", "保存容量を確認する", "安全に空きを作る", "再試行する"],
    commonConcepts: ["エラー本文", "原因候補", "詳細", "保存容量", "再試行"],
    environmentOperations: environmentOperations(
      [["ダイアログの本文と詳細を読む", "設定のStorageを開く", "不要な練習ファイルをRecycle Binへ移して再試行する"], "通信の再試行では容量不足は直りません。"],
      [["アラート本文を読む", "システム設定のStorageを見る", "練習ファイルをTrashへ移して再試行する"], "Finderの情報を見るからサイズも確認できます。"],
      [["アラートを読む", "iPhoneストレージを確認する", "練習データを整理して再試行する"], "Appを取り除くことと削除は異なります。"],
      [["通知またはダイアログを読む", "設定のストレージを見る", "練習データを整理して再試行する"], "設定名はメーカーで異なります。"],
    ),
    hints: progressiveHints(
      "表示された文の中から、『何が足りないか』を探しましょう。",
      "今回は通信ではなく『保存容量』が手掛かりです。",
      "詳細を読み、設定のStorageで空きを確認し、練習ファイルをRecycle Binへ移して再試行します。",
      "アラートを読み、設定のStorageで空きを確認し、練習ファイルをTrashへ移して再試行します。",
      "アラートを読み、iPhoneストレージで練習データを整理して再試行します。",
      "エラーを読み、設定のストレージで練習データを整理して再試行します。",
    ),
    afterCompletion: "エラーを責める文ではなく、次の確認を示す手掛かりとして読めます。",
    xp: 70,
    danger: danger("yellow", "空きを作るときは練習データだけを選び、完全削除はしません。"),
    success: missionSuccess(
      "容量不足を原因として確認し、安全に空きを作って保存へ再成功している。",
      [
        ["causeCategory", "原因分類がstorageになっている"],
        ["spaceRecovered", "必要な保存容量が確保されている"],
        ["retrySucceeded", "写真保存の再試行が成功している"],
      ],
      [
        ["errorInspected", "observation", "閉じる前にエラー本文を確認した"],
        ["safeCleanupUsed", "decision", "元へ戻せる練習データ整理を選んだ"],
      ],
    ),
  },
  {
    id: "wifi-recovery",
    areaId: "solve-problems",
    order: 26,
    title: "つながらないを切り分ける",
    mission: "接続表示を確かめ、まちのWi-Fiへつなぎ直しましょう。",
    objective: "端末、Wi-Fi、サイトのどこに問題があるか順に確認する。",
    competency: "接続表示、機内モード、ネットワーク、別サイトで原因を分ける。",
    competencyIds: ["C2", "C6"],
    prerequisites: ["menu-discovery", "browser-search", "error-reading"],
    transferTo: ["help-search", "independent-troubleshoot"],
    guidance: "coach",
    estimatedMinutes: 9,
    interactions: ["wifi-recovery", "menu-discovery", "browser-search", "recovery"],
    realWorldActions: ["接続アイコンを見る", "機内モードを見る", "選択中Wi-Fiを見る", "正しいWi-Fiへつなぐ", "二つのページで確かめる"],
    commonConcepts: ["Wi-Fi", "機内モード", "接続先", "端末の問題", "サイトの問題"],
    environmentOperations: environmentOperations(
      [["タスクバーのクイック設定を開く", "Wi-Fiと機内モードを見る", "まちのWi-Fiへつなぐ"], "設定を一度に全部変えず、一項目ずつ確認します。"],
      [["メニューバーまたはコントロールセンターを開く", "Wi-Fi一覧を見る", "まちのWi-Fiへつなぐ"], "現在のネットワーク名を先に確認します。"],
      [["コントロールセンターで状態を見る", "設定でWi-Fi一覧を開く", "まちのWi-Fiへつなぐ"], "コントロールセンターは一時切断になる場合があります。"],
      [["クイック設定を開く", "Wi-Fiを長押しして詳細を見る", "まちのWi-Fiへつなぐ"], "クイック設定の配置はメーカーで異なります。"],
    ),
    hints: progressiveHints(
      "設定を変える前に、見える接続の印を一つずつ読みましょう。",
      "Wi-Fi、機内モード、現在のネットワーク名を確認します。",
      "タスクバーのクイック設定で機内モードを確認し、『まちのWi-Fi』を選んで二ページを開きます。",
      "コントロールセンターで状態を見て、『まちのWi-Fi』へつなぎ、二ページを開きます。",
      "コントロールセンターで状態を見て、設定から『まちのWi-Fi』へつなぎます。",
      "クイック設定のWi-Fiを長押しし、『まちのWi-Fi』へつないで二ページを開きます。",
    ),
    afterCompletion: "つながらない原因を一つずつ分け、必要な所だけ直せます。",
    xp: 70,
    danger: danger("yellow", "知らないネットワークにはつながらず、指定された練習Wi-Fiだけを選びます。"),
    success: missionSuccess(
      "接続表示を確認後、正しいWi-Fiへ接続し、二つの行き先を開けている。",
      [
        ["correctNetworkConnected", "まちのWi-Fiへ接続されている"],
        ["twoDestinationsVerified", "別々の二ページが開けている"],
      ],
      [
        ["indicatorsChecked", "observation", "接続と機内モードの表示を確認した"],
        ["airplaneModeHandled", "decision", "機内モードを不要に変更せず必要なら正しく解除した"],
      ],
    ),
  },
  {
    id: "help-search",
    areaId: "solve-problems",
    order: 27,
    title: "分からない操作を自分で調べる",
    mission: "文字が大きくなった理由を調べ、表示を戻しましょう。",
    objective: "環境、目的、症状を検索できる短い言葉へ変える。",
    competency: "公式ヘルプ、FAQ、設定検索から必要な一手を見つける。",
    competencyIds: ["C3", "C6", "C7"],
    prerequisites: ["search-refine", "source-check", "error-reading"],
    transferTo: ["alternate-solution", "independent-settings", "independent-troubleshoot"],
    guidance: "challenge",
    estimatedMinutes: 9,
    interactions: ["help-search", "search-refine", "source-check", "recovery"],
    realWorldActions: ["症状を言葉にする", "環境名を足す", "公式ヘルプを選ぶ", "該当見出しを読む", "表示を戻す"],
    commonConcepts: ["環境名", "症状", "公式ヘルプ", "FAQ", "該当見出し"],
    environmentOperations: environmentOperations(
      [["Windows Searchまたは設定検索を使う", "Microsoftサポート風ヘルプを開く", "表示倍率を戻す"], "設定内検索とWeb検索を使い分けます。"],
      [["Helpメニューまたは設定検索を使う", "Appleサポート風ヘルプを開く", "表示を戻す"], "Helpメニューは今のアプリに関する入口です。"],
      [["設定内検索またはユーザガイドを使う", "iOS版と症状を確認する", "表示を戻す"], "端末名やOS版を含めると探しやすくなります。"],
      [["設定内検索またはGoogle／メーカーのヘルプを使う", "機種名とAndroid版を見る", "表示を戻す"], "メーカーの案内が必要な場合があります。"],
    ),
    hints: progressiveHints(
      "『できない』ではなく、使っている環境と見えている症状を言葉にしましょう。",
      "環境名、文字、急に大きい、戻す、の語を使って公式ヘルプを探します。",
      "『Windows 文字 急に大きい 戻す』で検索し、公式ヘルプの表示倍率を開きます。",
      "『Mac 文字 急に大きい 戻す』で検索し、公式ヘルプの表示設定を開きます。",
      "『iPhone 文字 大きい 戻す』で設定内検索し、テキストサイズを開きます。",
      "機種名と『文字 大きい 戻す』で検索し、公式の表示設定を開きます。",
    ),
    afterCompletion: "困った状態を検索語へ変え、信頼できる助けから戻せます。",
    xp: 75,
    danger: danger("green", "公式ヘルプや設定を見る操作は安全に試せます。"),
    success: missionSuccess(
      "文脈を含む検索から信頼できる案内を読み、表示を元へ戻している。",
      [["settingRestored", "文字表示が元の倍率へ戻っている"]],
      [
        ["queryContainsContext", "interaction", "環境、目的、症状を含む検索語を作った"],
        ["trustedHelpOpened", "decision", "公式または信頼できるヘルプを開いた"],
        ["relevantSectionFound", "observation", "該当見出しを見つけた"],
      ],
    ),
  },
  {
    id: "alternate-solution",
    areaId: "solve-problems",
    order: 28,
    title: "別のやり方で目的を達成する",
    mission: "使えない方法を避け、指定文を別アプリへ移しましょう。",
    objective: "一つの経路が使えなくても、安全な別経路で同じ状態へ進む。",
    competency: "メニュー、ショートカット、共有、選択やり直しを置き換える。",
    competencyIds: ["C6", "C7"],
    prerequisites: ["app-switch", "context", "copy-paste", "help-search"],
    transferTo: ["independent-research", "independent-file", "independent-troubleshoot"],
    guidance: "challenge",
    estimatedMinutes: 10,
    interactions: ["alternate-solution", "copy-paste", "context-menu", "app-switch", "recovery"],
    realWorldActions: ["主経路が使えないと確認する", "目的を言い換える", "別の入口を探す", "同じ最終状態へ進む"],
    commonConcepts: ["目的と手順", "代替経路", "メニュー", "ショートカット", "共有"],
    environmentOperations: environmentOperations(
      [["右クリックが使えないことを確認する", "リボン、三点、Ctrl+C/Vのいずれかを使う"], "正解は一つではなく、同じ最終状態で判定します。"],
      [["Controlクリックが使えないことを確認する", "EditメニューまたはCommand+C/Vを使う"], "上部メニューも操作の入口です。"],
      [["編集メニューが出ないことを確認する", "選択をやり直すか共有シートを使う"], "共有でメモへ渡す経路もあります。"],
      [["選択ツールバーが使えないことを確認する", "共有またはGboardクリップボードを使う"], "別経路でも元の内容を守ります。"],
    ),
    hints: progressiveHints(
      "覚えたボタンではなく、最後に何をしたいかを一文にしましょう。",
      "コピーの別入口として、上部メニュー、ショートカット、共有を探します。",
      "右クリックをやめ、Ctrl+C/Vまたは三点メニューで同じ内容を移します。",
      "Controlクリックをやめ、Command+C/VまたはEditメニューを使います。",
      "選択をやり直すか共有シートからメモへ渡します。",
      "共有またはGboardクリップボードからメモへ渡します。",
    ),
    afterCompletion: "一つの手順が使えなくても、目的を保って別の道を選べます。",
    xp: 80,
    danger: danger("yellow", "別経路でも、共有先や元の文章が変わらないか確認します。"),
    success: missionSuccess(
      "主経路が使えない状態から、許可された別経路で同じ目標状態へ到達している。",
      [["targetState", "指定文が別アプリへ正しく移っている"]],
      [
        ["primaryRouteUnavailable", "observation", "主経路が使えないと確認した"],
        ["alternativeRouteId", "interaction", "許可された代替経路を使った"],
        ["originalPreserved", "decision", "元の文章を保持した"],
      ],
    ),
  },
  {
    id: "independent-research",
    areaId: "independent-challenge",
    order: 29,
    title: "営業時間を自力で確かめる",
    mission: "明日の市民交流館の時間を、根拠と一緒に答えましょう。",
    objective: "検索、比較、公式性、新しさを組み合わせて答えを作る。",
    competency: "手順なしで情報を探し、矛盾を解き、根拠を記録する。",
    competencyIds: ["C3", "C5", "C7"],
    prerequisites: ["source-check", "suspicious-message", "help-search", "alternate-solution"],
    transferTo: ["independent-file", "independent-troubleshoot"],
    guidance: "challenge",
    estimatedMinutes: 12,
    interactions: ["independent-research", "browser-search", "search-refine", "tabs-compare", "source-check", "app-switch"],
    realWorldActions: ["自分で検索語を作る", "複数結果を開く", "公式性と日付を見る", "古い情報との矛盾を解く", "根拠を記録する"],
    commonConcepts: ["目的の分解", "公式情報", "対象日", "更新日", "矛盾", "根拠"],
    environmentOperations: environmentOperations(
      [["標準ブラウザで調べる", "タブまたは別ウィンドウで比較する", "メモへ根拠を残す"], "Ctrl系操作やタスクバーは使っても使わなくても構いません。"],
      [["標準ブラウザで調べる", "タブまたは別画面で比較する", "メモへ根拠を残す"], "Command系操作やDockは選べる経路です。"],
      [["Safari風ブラウザで調べる", "タブまたはアプリ切替で比較する", "メモへ根拠を残す"], "共通の情報判断基準はPCと変わりません。"],
      [["標準ブラウザで調べる", "タブまたは履歴で比較する", "メモへ根拠を残す"], "ブラウザの違いより発信元と日付を優先します。"],
    ),
    hints: progressiveHints(
      "答えに必要な物を『場所』『対象日』『時間』『変更の有無』へ分けましょう。",
      "公式ページ、更新日、古いブログとの違いを確かめます。",
      "関連する『探して確かめる』ミッションを振り返り、公式ページと日付を根拠に答えます。",
      "関連する『探して確かめる』ミッションを振り返り、公式ページと日付を根拠に答えます。",
      "道具箱で検索と発信元の確認方法を調べ、公式情報をメモします。",
      "道具箱で検索と発信元の確認方法を調べ、公式情報をメモします。",
    ),
    afterCompletion: "手順を示されなくても、最新の公式情報を根拠つきで確かめられます。",
    xp: 90,
    danger: danger("yellow", "検索結果の古い時間を使わず、対象日と更新日を確認します。"),
    success: missionSuccess(
      "対象日の営業時間と臨時変更を、公式で新しい根拠とともに記録している。",
      [
        ["correctDate", "回答の対象日が明日になっている"],
        ["answerRecorded", "正しい営業時間と変更有無が記録されている"],
      ],
      [
        ["officialSourceUsed", "decision", "公式情報を主要根拠に選んだ"],
        ["freshnessChecked", "comparison", "更新日を確認した"],
        ["conflictResolved", "explanation", "古いブログとの違いを説明した"],
      ],
    ),
  },
  {
    id: "independent-file",
    areaId: "independent-challenge",
    order: 30,
    title: "受け取った資料を整理して返す",
    mission: "申込書を保存、整理、添付し、返信の準備を終えましょう。",
    objective: "受信から送信前確認までを、一続きの生活課題として行う。",
    competency: "保存、名称変更、移動、版確認、添付、宛先確認を統合する。",
    competencyIds: ["C2", "C4", "C5", "C6", "C7"],
    prerequisites: ["attach-review", "error-reading", "alternate-solution"],
    transferTo: ["independent-troubleshoot"],
    guidance: "challenge",
    estimatedMinutes: 14,
    interactions: ["independent-file", "file-organize", "download-locate", "attach-review", "app-switch", "recovery"],
    realWorldActions: ["メールから一度保存する", "意味のある名前へ変える", "指定フォルダへ移す", "正しい版を添付する", "宛先を確認する"],
    commonConcepts: ["受信", "保存", "版", "ファイル名", "整理", "返信", "送信前確認"],
    environmentOperations: environmentOperations(
      [["メールから保存する", "File Explorerで名前と場所を整える", "返信へ添付して宛先を確認する"], "Explorerとメールの間は自由な経路で移動できます。"],
      [["メールから保存する", "Finderで名前と場所を整える", "返信へ添付して確認する"], "Finderからのドラッグ添付も正解です。"],
      [["メールまたは共有からFilesへ保存する", "Filesで名称変更と移動をする", "共有またはメールから添付する"], "PhotosとFilesを選び分けます。"],
      [["メールまたは共有からFiles系アプリへ保存する", "名称変更と移動をする", "返信へ添付する"], "共有シートとシステム選択のどちらも正解です。"],
    ),
    hints: progressiveHints(
      "作業を『受け取る』『後で見つける』『正しく返す』へ分けましょう。",
      "保存は一度、名前は2026自治会申込書_記入済.pdf、場所と版と宛先を確認します。",
      "ファイル整理と添付レビューのミッションを振り返り、最終状態を一つずつ確認します。",
      "ファイル整理と添付レビューのミッションを振り返り、最終状態を一つずつ確認します。",
      "道具箱でFilesと共有を調べ、保存、名称変更、移動、添付、宛先確認の順に状態を見ます。",
      "道具箱でFiles系アプリと共有を調べ、保存、整理、添付、宛先確認の状態を見ます。",
    ),
    afterCompletion: "受け取った資料を後から見つけられる形にし、正しい相手へ準備できます。",
    xp: 95,
    danger: danger("red", "外部送信は行いません。正しい版、添付、宛先を確認して模擬確定します。"),
    success: missionSuccess(
      "指定名と場所へ一度保存し、正しい版だけを正しい宛先の返信へ添付している。",
      [
        ["meaningfulFilename", "名前が2026自治会申込書_記入済.pdfになっている"],
        ["correctFolder", "指定フォルダへ整理されている"],
        ["correctVersionAttached", "最新版だけが返信へ添付されている"],
      ],
      [
        ["savedOnce", "interaction", "申込書を一度保存した"],
        ["recipientReviewed", "decision", "返信先を確認した"],
        ["oldVersionRejected", "comparison", "似た旧版を除外した"],
      ],
    ),
  },
  {
    id: "independent-settings",
    areaId: "independent-challenge",
    order: 31,
    title: "読みやすく設定して戻す",
    mission: "表示を読みやすくし、崩れたら一段戻しましょう。",
    objective: "未知の設定画面で、検索、プレビュー、取り消しを使う。",
    competency: "設定名を暗記せず、可逆性を確認しながら自分に合う値を選ぶ。",
    competencyIds: ["C2", "C6", "C7"],
    prerequisites: ["menu-discovery", "recovery", "help-search"],
    transferTo: ["independent-troubleshoot"],
    guidance: "challenge",
    estimatedMinutes: 12,
    interactions: ["independent-settings", "menu-discovery", "help-search", "recovery"],
    realWorldActions: ["設定を自分で探す", "文字とコントラストを試す", "プレビューを見る", "崩れを観察する", "一段戻す"],
    commonConcepts: ["アクセシビリティ", "表示", "プレビュー", "可逆性", "自分に合う値"],
    environmentOperations: environmentOperations(
      [["Accessibilityまたは設定検索を使う", "Text sizeとContrastを調整する", "はみ出したら一段戻す"], "設定名や場所は版で変わるため検索も使います。"],
      [["AccessibilityのDisplayを探す", "文字とコントラストを試す", "崩れたら戻す"], "プレビューと元の値を見比べます。"],
      [["画面表示とテキストサイズを探す", "読みやすさを試す", "はみ出したら一段戻す"], "さらに大きな文字はアクセシビリティ側にあります。"],
      [["表示サイズとテキストを探す", "文字とコントラストを試す", "崩れたら戻す"], "設定名と最大値はメーカーで異なります。"],
    ),
    hints: progressiveHints(
      "設定の場所を暗記せず、目的の言葉で探しましょう。",
      "『文字』『表示』『アクセシビリティ』で検索し、プレビューを見ます。",
      "関連するメニュー発見、復旧、ヘルプ検索を振り返り、読みやすさと崩れの両方を確認します。",
      "関連するメニュー発見、復旧、ヘルプ検索を振り返り、読みやすさと崩れの両方を確認します。",
      "設定内検索でテキストサイズを開き、最大値から一段戻して見やすい値を選びます。",
      "設定内検索で表示サイズを開き、最大値から一段戻して見やすい値を選びます。",
    ),
    afterCompletion: "初めての設定画面でも、試し、見比べ、合わなければ戻せます。",
    xp: 95,
    danger: danger("yellow", "表示変更は戻せます。元の値を確認してから試します。"),
    success: missionSuccess(
      "目的の表示設定を自分で見つけ、読みやすさを満たし、はみ出しから復旧している。",
      [
        ["readabilityTargetMet", "文字とコントラストが読みやすさ条件を満たしている"],
        ["layoutFitsViewport", "内容が画面幅へ収まっている"],
      ],
      [
        ["settingsFoundWithoutExactPathHint", "interaction", "具体経路なしで設定を見つけた"],
        ["previewUsed", "observation", "変更前にプレビューを確認した"],
        ["overflowRecovered", "recovery", "最大値の崩れから一段戻した"],
      ],
    ),
  },
  {
    id: "independent-troubleshoot",
    areaId: "independent-challenge",
    order: 32,
    title: "予期しない問題を解決する",
    mission: "追加できない写真を、安全に申込フォームへ準備しましょう。",
    objective: "初見の問題を観察、切り分け、調査、代替経路、復旧で解く。",
    competency: "C1からC7を統合し、選んだ理由まで説明する。",
    competencyIds: ["C1", "C2", "C3", "C4", "C5", "C6", "C7"],
    prerequisites: ["independent-research", "independent-file", "independent-settings"],
    transferTo: [],
    guidance: "challenge",
    estimatedMinutes: 15,
    interactions: ["independent-troubleshoot", "error-reading", "permission-decision", "file-concepts", "attach-review", "help-search", "alternate-solution", "recovery"],
    realWorldActions: ["エラーを読む", "形式、場所、権限、容量を切り分ける", "必要ならヘルプを探す", "元写真を守る", "添付プレビューまで進む", "理由を振り返る"],
    commonConcepts: ["診断", "原因候補", "安全な試行", "原本保護", "代替経路", "振り返り"],
    environmentOperations: environmentOperations(
      [["File Explorerとファイル選択を使う", "権限またはStorageを確認する", "原本を残して添付プレビューへ進む"], "原因は形式、場所、権限、容量から一つ出題されます。"],
      [["Finderとファイル選択を使う", "PrivacyまたはStorageを確認する", "原本を残して添付する"], "原因尺度は他環境と同じです。"],
      [["Photos、Files、権限設定を使い分ける", "原本を残して共有または選択から添付する"], "出題原因に必要な所だけ変更します。"],
      [["Photos、Files系アプリ、権限設定を使い分ける", "原本を残して添付する"], "メーカー差があっても原因分類は共通です。"],
    ),
    hints: progressiveHints(
      "まず『できなかったこと』『表示されたこと』『変えずに守る物』を書き出しましょう。",
      "形式、保存場所、権限、容量を一つずつ確認し、原因に合う過去ミッションを探します。",
      "道具箱または関連ミッションを選び、確認した証拠を残してから安全な経路を試します。",
      "道具箱または関連ミッションを選び、確認した証拠を残してから安全な経路を試します。",
      "公式ヘルプ風ページと関連ミッションを使い、原本を残したまま添付プレビューへ進みます。",
      "公式ヘルプ風ページと関連ミッションを使い、原本を残したまま添付プレビューへ進みます。",
    ),
    afterCompletion: "初めての問題でも、観察した証拠から安全な方法を選び、理由を説明できます。",
    xp: 120,
    danger: danger("red", "元写真を削除・上書きせず、外部送信前の添付プレビューまでで止まります。"),
    success: missionSuccess(
      "出題された原因を特定し、原本を守ったまま正しい写真を添付プレビューへ進めている。",
      [
        ["targetAttachment", "正しい写真が添付プレビューにある"],
        ["originalPreserved", "元写真が変更されず残っている"],
      ],
      [
        ["diagnosisEvidence", "explanation", "原因を示す証拠を記録した"],
        ["safeActions", "decision", "危険な確定を避けて必要な操作だけ選んだ"],
        ["reflectionRecorded", "explanation", "見た物と選んだ理由を短く振り返った"],
      ],
    ),
  },
];

export const journeyMissionIds: readonly MissionId[] = journeyMissions.map(
  (mission) => mission.id,
);

const missionById = new Map<MissionId, MissionDefinition>(
  journeyMissions.map((mission) => [mission.id, mission]),
);

const areaById = new Map<JourneyAreaId, JourneyArea>(
  journeyAreas.map((area) => [area.id, area]),
);

export function isLearningEnvironment(value: string): value is LearningEnvironment {
  return learningEnvironments.includes(value as LearningEnvironment);
}

export function getMission(id: string): MissionDefinition | undefined {
  return missionById.get(id as MissionId);
}

export function getArea(id: string): JourneyArea | undefined {
  return areaById.get(id as JourneyAreaId);
}

export function getMissionsForArea(areaId: JourneyAreaId | string): readonly MissionDefinition[] {
  const area = getArea(areaId);
  if (!area) return [];
  return area.missionIds
    .map((missionId) => missionById.get(missionId))
    .filter((mission): mission is MissionDefinition => Boolean(mission));
}

export function getAreaForMission(missionId: MissionId | string): JourneyArea | undefined {
  const mission = getMission(missionId);
  return mission ? getArea(mission.areaId) : undefined;
}

export function makeMissionPath(
  environment: LearningEnvironment,
  missionId: MissionId,
): string {
  return `/mission/${environment}/${missionId}`;
}

export function getNextMission(missionId: MissionId | string): MissionDefinition | undefined {
  const index = journeyMissions.findIndex((mission) => mission.id === missionId);
  return index >= 0 ? journeyMissions[index + 1] : undefined;
}

export function getPreviousMission(missionId: MissionId | string): MissionDefinition | undefined {
  const index = journeyMissions.findIndex((mission) => mission.id === missionId);
  return index > 0 ? journeyMissions[index - 1] : undefined;
}

export function getEnvironmentOperation(
  missionId: MissionId | string,
  environment: LearningEnvironment,
): EnvironmentOperation | undefined {
  return getMission(missionId)?.environmentOperations[environment];
}

export function makeJourneyPath(environment: LearningEnvironment): string {
  return `/journey/${environment}`;
}

export function makeAreaPath(
  environment: LearningEnvironment,
  areaId: JourneyAreaId,
): string {
  return `/journey/${environment}/area/${areaId}`;
}

export { environmentLabels };
