import type { StageDefinition } from "../lib/types";

export const stages: StageDefinition[] = [
  {
    id: "w1-pc-copy-paste",
    worldId: "world-1",
    device: "pc",
    order: 1,
    code: "1-P",
    title: "メモへコピーして貼り付けよう",
    description:
      "練習メモを開き、見本の文章をコピーして別の欄へ貼り付けます。",
    objective: "見本の『集合は10時です』を、下のメモ欄へコピーしてください。",
    guidance: "guided",
    estimatedMinutes: 3,
    targetActions: ["open-notes", "copy-text", "paste-text"],
    hints: [
      "まず、デスクトップにある『メモ』を開いてみましょう。",
      "見本の文章を選ぶと、『コピー』というボタンが見つかります。",
      "下のメモ欄を選び、『貼り付け』を押しましょう。",
    ],
    glossaryTermIds: ["app", "copy", "paste"],
    xp: 40,
    safetyNote:
      "このメモは練習用です。コピーや貼り付けを何度試しても、実際の文章には影響しません。",
    competencyIds: ["safe-experiment", "observation"],
    completionMessage:
      "コピーした内容を別の場所で使えました。この考え方は多くのアプリで共通です。",
  },
  {
    id: "w1-mobile-copy-paste",
    worldId: "world-1",
    device: "mobile",
    order: 2,
    code: "1-M",
    title: "スマホのメモへ貼り付けよう",
    description:
      "案内文をコピーし、練習メモへ貼り付けてからホームへ戻ります。",
    objective: "『受付は2階です』をコピーし、メモへ貼り付けてください。",
    guidance: "guided",
    estimatedMinutes: 3,
    targetActions: ["copy-text", "open-notes", "paste-text", "go-home"],
    hints: [
      "案内文を長めに押すと、使える操作が表示されます。",
      "『コピー』を選んだら、ホーム画面から『メモ』を開きましょう。",
      "空いている欄を押し、『貼り付け』を選びます。最後にホームへ戻りましょう。",
    ],
    glossaryTermIds: ["copy", "paste", "home-screen", "app"],
    xp: 40,
    safetyNote:
      "練習用スマートフォンの中だけで動きます。実際の端末のクリップボードは使いません。",
    competencyIds: ["safe-experiment", "observation"],
    completionMessage:
      "長押しで操作を見つけ、メモへ貼り付けられました。分からないときは少し長く押す方法もあります。",
  },
  {
    id: "w2-pc-find-settings",
    worldId: "world-2",
    device: "pc",
    order: 1,
    code: "2-P",
    title: "文字を大きくする場所を探そう",
    description:
      "最初に出ている案内を閉じ、歯車のマークから表示設定を探します。",
    objective: "案内を閉じて、画面の文字を『大きい』に変更してください。",
    guidance: "guided",
    estimatedMinutes: 4,
    targetActions: ["dismiss-popup", "open-settings", "text-larger"],
    hints: [
      "まず、中央にある小さな案内を閉じて、画面全体を見てみましょう。",
      "画面の右上に、歯車に似たマークがあります。",
      "歯車を押し、『文字の大きさ』から『大きい』を選びましょう。",
    ],
    glossaryTermIds: ["popup", "settings", "window"],
    xp: 45,
    safetyNote:
      "設定画面を見るだけなら比較的安全です。練習中の変更はいつでも元に戻せます。",
    competencyIds: ["observation", "safe-experiment"],
    completionMessage:
      "歯車を手がかりに設定を見つけられました。歯車は多くの画面で設定を表します。",
  },
  {
    id: "w2-mobile-more-menu",
    worldId: "world-2",
    device: "mobile",
    order: 2,
    code: "2-M",
    title: "三点メニューの中を見てみよう",
    description:
      "画面の三点マークからメニューを開き、表示設定を見つけます。",
    objective: "三点マークを使って、記事の文字を大きくしてください。",
    guidance: "supported",
    estimatedMinutes: 4,
    targetActions: ["open-more", "open-settings", "text-larger", "go-back"],
    hints: [
      "画面の上側に、点が三つ並んだマークがないか見てみましょう。",
      "三点マークの中に『表示設定』があります。",
      "『文字の大きさ』を変更したら、左向きの戻るを押して記事へ戻りましょう。",
    ],
    glossaryTermIds: ["more-menu", "menu", "settings", "scroll"],
    xp: 45,
    safetyNote:
      "三点メニューを開くだけで何かが送信されたり削除されたりすることはありません。",
    competencyIds: ["observation", "safe-experiment", "transfer"],
    completionMessage:
      "三点マークを手がかりに、見えていなかった機能を見つけられました。",
  },
  {
    id: "w3-pc-search-tabs",
    worldId: "world-3",
    device: "pc",
    order: 1,
    code: "3-P",
    title: "検索結果をタブで比べよう",
    description:
      "架空のブラウザで検索し、二つの結果を別々のタブで開いて比べます。",
    objective: "『さくら公園 開園時間』を検索し、二つの案内を比べて正しい時間を見つけてください。",
    guidance: "supported",
    estimatedMinutes: 5,
    targetActions: [
      "open-browser",
      "search-web",
      "open-result",
      "switch-tab",
      "go-back",
    ],
    hints: [
      "地球のようなマークの『ブラウザ』から検索できます。",
      "検索結果を開いたあと、上に並ぶ見出しを使うと別のページへ切り替えられます。",
      "『公式案内』と『去年のお知らせ』を比べ、日付が新しい方を確かめましょう。",
    ],
    glossaryTermIds: ["browser", "search", "link", "tab", "url"],
    xp: 50,
    safetyNote:
      "表示されるサイトと検索結果はすべて練習用で、外部サイトには移動しません。",
    competencyIds: ["research", "observation", "recovery"],
    completionMessage:
      "複数の情報を比べられました。検索では、情報の新しさや発信元も大切な手がかりです。",
  },
  {
    id: "w3-mobile-search-back",
    worldId: "world-3",
    device: "mobile",
    order: 2,
    code: "3-M",
    title: "検索して、戻ってみよう",
    description:
      "スマホの架空ブラウザで情報を探し、リンク先から検索結果へ戻ります。",
    objective: "『市民センター 休館日』を検索し、休館日を確認してホームへ戻ってください。",
    guidance: "supported",
    estimatedMinutes: 4,
    targetActions: [
      "open-browser",
      "search-web",
      "open-result",
      "go-back",
      "go-home",
    ],
    hints: [
      "ホーム画面の『ブラウザ』を開き、調べたい言葉を短く入力しましょう。",
      "結果の中から『市民センター公式案内』を開いてみましょう。",
      "確認できたら、練習ブラウザの戻るで検索結果へ戻り、ホームへ戻ります。",
    ],
    glossaryTermIds: ["browser", "search", "link", "home-screen"],
    xp: 50,
    safetyNote:
      "検索窓には練習用の言葉だけを入れます。氏名や住所などの個人情報は入力しません。",
    competencyIds: ["research", "recovery", "observation"],
    completionMessage:
      "検索して情報を確認し、元の画面へ戻れました。迷ったときに戻る操作が使えます。",
  },
  {
    id: "w4-pc-password-recovery",
    worldId: "world-4",
    device: "pc",
    order: 1,
    code: "4-P",
    title: "パスワードを忘れたとき",
    description:
      "練習用ログイン画面から再設定を選び、疑似メールに届く認証コードを確認します。",
    objective: "練習アカウントの再設定を始め、メールに届いた認証コードを確認してください。",
    guidance: "supported",
    estimatedMinutes: 5,
    targetActions: [
      "open-account",
      "password-help",
      "open-mail",
      "go-back",
    ],
    hints: [
      "ログイン欄の近くにある『パスワードを忘れた方』を探しましょう。",
      "再設定を始めると、練習用メールに認証コードが届きます。",
      "メールでコードを確認したら、戻るで再設定画面へ戻りましょう。",
    ],
    glossaryTermIds: [
      "account",
      "login",
      "password",
      "authentication-code",
      "email",
    ],
    xp: 55,
    safetyNote:
      "本物のIDやパスワードは絶対に入力しないでください。ここで使う情報はすべて架空です。",
    competencyIds: ["recovery", "safe-experiment", "observation"],
    completionMessage:
      "忘れたときの入口を自分で見つけられました。分からなくても、再設定の方法があります。",
  },
  {
    id: "w4-mobile-switch-account",
    worldId: "world-4",
    device: "mobile",
    order: 2,
    code: "4-M",
    title: "使うアカウントを確かめよう",
    description:
      "プロフィールから練習アカウントを切り替え、危険な操作では立ち止まります。",
    objective: "『練習A』から『練習B』へ切り替え、アカウント削除はキャンセルしてください。",
    guidance: "supported",
    estimatedMinutes: 5,
    targetActions: ["open-account", "switch-account", "safe-cancel", "go-home"],
    hints: [
      "画面上の丸い人物マークから、現在のアカウントを確認できます。",
      "名前の横にある切り替えマークを押し、『練習B』を選びましょう。",
      "『アカウント削除』は注意が必要です。確認画面の説明を読み、キャンセルしましょう。",
    ],
    glossaryTermIds: ["account", "user-id", "logout", "safe-operation"],
    xp: 55,
    safetyNote:
      "削除、購入、公開、送信は現実では慎重に確認する操作です。今回は削除を実行せずキャンセルします。",
    competencyIds: ["safe-experiment", "observation", "transfer"],
    completionMessage:
      "使っているアカウントを確認し、注意が必要な操作で立ち止まれました。",
  },
  {
    id: "w5-pc-download-attach",
    worldId: "world-5",
    device: "pc",
    order: 1,
    code: "5-P",
    title: "資料を見つけて添付しよう",
    description:
      "練習サイトの資料を取得し、ファイル画面で移動してから疑似メールへ添付します。",
    objective: "『参加案内.pdf』を『提出用』フォルダへ移動し、練習メールに添付してください。",
    guidance: "supported",
    estimatedMinutes: 6,
    targetActions: [
      "open-browser",
      "open-result",
      "open-files",
      "select-file",
      "move-file",
      "open-mail",
      "attach-file",
    ],
    hints: [
      "ブラウザの案内ページにある『参加案内.pdf』を開いてみましょう。",
      "ファイル画面の『ダウンロード』に資料があります。選んで『提出用』へ移動します。",
      "メールのクリップ形のマークから、『提出用』の資料を選びましょう。",
    ],
    glossaryTermIds: [
      "download",
      "file",
      "folder",
      "attachment",
      "email",
    ],
    xp: 60,
    safetyNote:
      "資料、フォルダ、メールはすべて練習用です。実際のファイルの移動や送信は行いません。",
    competencyIds: ["observation", "transfer", "safe-experiment"],
    completionMessage:
      "ダウンロード後の保存場所を見つけ、必要な場所へ移動して添付できました。",
  },
  {
    id: "w5-mobile-share-attach",
    worldId: "world-5",
    device: "mobile",
    order: 2,
    code: "5-M",
    title: "写真を選んで共有しよう",
    description:
      "練習写真を選択し、共有先としてメールを選び、下書きに添付します。",
    objective: "『公園の地図』の写真を選び、練習メールの下書きへ添付してください。",
    guidance: "supported",
    estimatedMinutes: 5,
    targetActions: [
      "open-files",
      "select-file",
      "share-photo",
      "open-mail",
      "attach-file",
      "safe-cancel",
    ],
    hints: [
      "『写真とファイル』を開き、『公園の地図』を選びましょう。",
      "共有マークを押すと、渡す先のアプリを選べます。",
      "『メール』を選び、添付を確認したら、送信はせず下書きに戻りましょう。",
    ],
    glossaryTermIds: ["file", "attachment", "share", "email", "upload"],
    xp: 60,
    safetyNote:
      "共有や送信の前には、相手と内容を確認します。この練習では送信せず、安全にキャンセルします。",
    competencyIds: ["safe-experiment", "transfer", "observation"],
    completionMessage:
      "写真を選び、共有先と添付内容を確認できました。送る前に立ち止まることも大切です。",
  },
  {
    id: "w6-pc-hidden-button",
    worldId: "world-6",
    device: "pc",
    order: 1,
    code: "6-P",
    title: "ボタンが見つからない！",
    description:
      "表示が狭くなった練習画面でエラーを読み、ヘルプから解決方法を探します。",
    objective: "表示されているメッセージを読み、ヘルプで調べて保存画面へ戻ってください。",
    guidance: "supported",
    estimatedMinutes: 6,
    targetActions: [
      "read-error",
      "open-help",
      "search-help",
      "dismiss-popup",
      "go-back",
    ],
    hints: [
      "まず、表示された文章を最後まで読んでみましょう。番号や大事な言葉が手がかりになります。",
      "『ヘルプ』で、メッセージにある『保存ボタン 見つからない』を検索してみましょう。",
      "案内を閉じ、画面を下へ動かしてから戻ると、保存画面をもう一度確認できます。",
    ],
    glossaryTermIds: ["error-message", "help", "search", "scroll", "undo"],
    xp: 65,
    safetyNote:
      "エラーは『壊れた』という意味とは限りません。文章を読み、分からない語を調べれば大丈夫です。",
    competencyIds: ["research", "recovery", "observation"],
    completionMessage:
      "エラーを手がかりに、自分で調べて元の作業へ戻れました。",
  },
  {
    id: "w6-mobile-ask-for-help",
    worldId: "world-6",
    device: "mobile",
    order: 2,
    code: "6-M",
    title: "AIに伝わる質問を作ろう",
    description:
      "エラーメッセージを読み、ヘルプ検索でも解決しないときの質問文を組み立てます。",
    objective: "エラー番号、やりたいこと、試したことを入れて、練習AIへの質問を書いてください。",
    guidance: "supported",
    estimatedMinutes: 6,
    targetActions: ["read-error", "open-help", "search-help", "write-question"],
    hints: [
      "エラー画面の『E-204』と、直前にしていた操作を確認しましょう。",
      "ヘルプで『E-204 ファイル 開けない』と検索し、試せる方法を一つ確認します。",
      "質問には『何をしたいか』『何が表示されたか』『何を試したか』の三つを書きましょう。",
    ],
    glossaryTermIds: ["error-message", "help", "search", "ai", "file"],
    xp: 65,
    safetyNote:
      "AIへ質問するときも、氏名、住所、本物のIDやパスワードなどの個人情報は書きません。",
    competencyIds: ["research", "transfer", "independent-exploration"],
    completionMessage:
      "状況を整理して質問できました。相手に伝わる質問を作ることも、自分で解決する力です。",
  },
  {
    id: "w7-pc-independent-file",
    worldId: "world-7",
    device: "pc",
    order: 1,
    code: "7-P",
    title: "目的だけチャレンジ：資料を整理",
    description:
      "細かな案内なしで、表示設定、検索、ファイル操作を組み合わせます。",
    objective: "文字を大きくし、『防災案内.pdf』を探して『あとで読む』フォルダへ移動してください。",
    guidance: "independent",
    estimatedMinutes: 8,
    targetActions: [
      "open-settings",
      "text-larger",
      "open-browser",
      "search-web",
      "open-result",
      "open-files",
      "select-file",
      "move-file",
    ],
    hints: [
      "必要な操作は一つとは限りません。目的を『見やすくする』『探す』『整理する』に分けてみましょう。",
      "表示は設定、資料はブラウザ、保存後の場所はファイル画面から確認できます。",
      "設定で文字を大きくし、ブラウザで資料を開き、ファイル画面で『あとで読む』へ移動します。",
    ],
    glossaryTermIds: ["settings", "browser", "search", "download", "folder"],
    xp: 75,
    safetyNote:
      "分からない場所を開く、戻る、設定を見ることは安全に試しやすい操作です。削除や送信は行いません。",
    competencyIds: [
      "independent-exploration",
      "transfer",
      "research",
      "safe-experiment",
    ],
    completionMessage:
      "複数の画面を自分で行き来し、目的を達成できました。初めての画面でも手がかりを探せています。",
  },
  {
    id: "w7-mobile-independent-research",
    worldId: "world-7",
    device: "mobile",
    order: 2,
    code: "7-M",
    title: "目的だけチャレンジ：情報をメモ",
    description:
      "検索、コピー、アプリの切り替えを組み合わせ、必要な情報を残します。",
    objective: "『星空観察会』の開始時刻を調べ、練習メモへコピーして保存してください。",
    guidance: "independent",
    estimatedMinutes: 8,
    targetActions: [
      "open-browser",
      "search-web",
      "open-result",
      "copy-text",
      "go-home",
      "open-notes",
      "paste-text",
    ],
    hints: [
      "まず、目的を『時刻を探す』と『メモに残す』に分けて考えてみましょう。",
      "ブラウザで公式案内を探し、必要な一文をコピーすると、別のアプリで使えます。",
      "開始時刻をコピーし、ホームからメモを開いて貼り付けましょう。",
    ],
    glossaryTermIds: ["browser", "search", "copy", "paste", "home-screen"],
    xp: 75,
    safetyNote:
      "検索結果には古い案内もあります。発信元と日付を確かめ、個人情報は入力しません。",
    competencyIds: [
      "independent-exploration",
      "transfer",
      "research",
      "observation",
    ],
    completionMessage:
      "検索した情報を別のアプリへ移して残せました。学んだ操作を組み合わせて使えています。",
  },
];
